#+TITLE: Pulp Science Fiction

* Lester Dent
** Introduction
 
   This is a formula, a master plot, for any 6000 word pulp story. It has worked
   on adventure, detective, western and war-air. It tells exactly where to put
   everything. It shows definitely just what must happen in each successive
   thousand words. No yarn of mine written to the formula has yet failed to sell.
   The business of building stories seems not much different from the business of
   building anything else. Here's how it starts:

   1. A DIFFERENT MURDER METHOD FOR VILLAIN
   TO USE

   2. A DIFFERENT THING FOR VILLAIN TO BE
   SEEKING

   3. A DIFFERENT LOCALE

   4. A MENACE WHICH IS TO HANG LIKE A CLOUD
   OVER HERO

   One of these DIFFERENT things would be nice, two better, three swell.
   It may help if they are fully in mind before tackling the rest. 

   A different murder method could be--different. Thinking of shooting, knifing,
   hydrocyanic, garroting, poison needles, scorpions, a few others, and writing
   them on paper gets them where they may suggest something. Scorpions and their
   poison bite? Maybe mosquitos or flies treated with deadly germs?

   If the victims are killed by ordinary methods, but found under strange and
   identical circumstances each time, it might serve, the reader of course not
   knowing until the end, that the method of murder is ordinary.

   Scribes who have their villain's victims found with butterflies, spiders or
   bats stamped on them could conceivably be flirting with this gag.

   Probably it won't do a lot of good to be too odd, fanciful or
   grotesque with murder methods. 

   The different thing for the villain to be after
   might be something other than jewels, the stolen bank loot, the pearls, or some
   other old ones. 

   Here, again one might get too bizarre.

   Unique locale? Easy. Selecting one that fits in with the murder method and
   the treasure--thing that villain wants-- makes it simpler, and it's also nice
   to use a familiair one, a place where you've lived or worked. So many
   pulpateers don't. It sometimes saves embarrassment to know nearly as much
   about the locale as the editor, or enough to fool him.

   Here's a nifty much used in faking local color. For a story laid in Egypt,
   say, author finds a book titled "Conversational Egyptian Easily Learned," or
   something like that. He wants a character to ask in Egyptian, "What's This is
   a formula, a master plot, for any 6000 word pulp story. It has worked on
   adventure, detective, western and war-air. It tells exactly where to put
   everything. It shows definitely just what must happen in each successive
   thousand words.

   What's the matter?" He looks in the book and finds, "El khabar, eyh?" To keep
   the reader from getting dizzy, it's perhaps wise to make it clear in some
   fashion, just what that means. Occasionally the text will tell this, or
   someone can repeat it in English. But it's a doubtful move to stop and tell
   the reader in so many words the English translation. The writer learns they
   have palm trees in Egypt. He looks in the book, finds the Egyptian for palm
   trees, and uses that. This kids editors and readers into thinking he knows
   something about Egypt.

   Here's the second installment of the master plot. Divide the 6000 word yarn
   into four 1500 word parts. In each 1500 word part, put the following:
   
** First 1500 Words
   1--First line, or as near thereto as possible, introduce the hero and swat
   him with a fistful of trouble. Hint at a mystery, a menace or a problem to be
   solved--something the hero has to cope with.

   2--The hero pitches in to cope with his fistful of trouble. (He tries to
   fathom the mystery, defeat the menace, or solve the problem.)

   3--Introduce ALL the other characters as soon as possible. Bring them on in
   action.

   4--Hero's endevours land him in an actual physical conflict near the end of
   the first 1500 words.

   5--Near the end of first 1500 words, there is a complete surprise twist in
   the plot development.

   SO FAR: Does it have SUSPENSE? Is there a MENACE to the hero? Does everything
   happen logically?

   At this point, it might help to recall that action should do something
   besides advance the hero over the scenery. Suppose the hero has learned the
   dastards of villains have seized somebody named Eloise, who can explain the
   secret of what is behind all these sinister events. The hero corners
   villains, they fight, and villains get away. Not so hot.

   Hero should accomplish something with his tearing around, if only to rescue
   Eloise, and surprise! Eloise is a ring-tailed monkey. The hero counts the
   rings on Eloise's tail, if nothing better comes to mind.

   They're not real. The rings are painted there. Why?

** Second 1500 Words

   1--Shovel more grief onto the hero.

   2--Hero, being heroic, struggles, and his struggles lead up to:

   3--Another physical conflict.

   4--A surprising plot twist to end the 1500 words.

   NOW: Does second part have SUSPENSE? Does the MENACE grow like a black cloud?
   Is the hero getting it in the neck? Is the second part logical?

   DON'T TELL ABOUT IT***Show how the thing looked. This is one of the secrets
   of writing; never tell the reader--show him. (He trembles, roving eyes,
   slackened jaw, and such.) MAKE THE READER SEE HIM.

   When writing, it helps to get at least one minor surprise to the printed
   page. It is reasonable to to expect these minor surprises to sort of inveigle
   the reader into keeping on. They need not be such profound efforts. One
   method of accomplishing one now and then is to be gently misleading. Hero is
   examining the murder room. The door behind him begins slowly to open. He does
   not see it. He conducts his examination blissfully. Door eases open, wider
   and wider, until--surprise! The glass pane falls out of the big window across
   the room. It must have fallen slowly, and air blowing into the room caused
   the door to open. Then what the heck made the pane fall so slowly? More
   mystery.

   Characterizing a story actor consists of giving him some things which make
   him stick in the reader's mind. TAG HIM.

   BUILD YOUR PLOTS SO THAT ACTION CAN BE CONTINUOUS.
** Third 1500 Words

   1--Shovel the grief onto the hero.

   2--Hero makes some headway, and corners the villain or somebody in:

   3--A physical conflict.

   4--A surprising plot twist, in which the hero preferably gets it in the neck
   bad, to end the 1500 words. DOES: It still have SUSPENSE? The MENACE getting
   blacker? The hero finds himself in a hell of a fix? It all happens logically?

   These outlines or master formulas are only something to make you certain of
   inserting some physical conflict, and some genuine plot twists, with a little
   suspense and menace thrown in. Without them, there is no pulp story. These
   physical conflicts in each part might be DIFFERENT, too. If one fight is with
   fists, that can take care of the pugilism until next the next yarn. Same for
   poison gas and swords. There may, naturally, be exceptions. A hero with a
   peculiar punch, or a quick draw, might use it more than once.

   The idea is to avoid monotony.

   ACTION: Vivid, swift, no words wasted. Create suspense, make the reader see
   and feel the action. 

   ATMOSPHERE: Hear, smell, see, feel and taste.
   DESCRIPTION: Trees, wind, scenery and water. 

   THE SECRET OF ALL WRITING IS TO MAKE EVERY WORD COUNT.
** Fourth 1500 Words

   1--Shovel the difficulties more thickly upon the hero.

   2--Get the hero almost buried in his troubles. (Figuratively, the villain has
   him prisoner and has him framed for a murder rap; the girl is presumably
   dead, everything is lost, and the DIFFERENT murder method is about to dispose
   of the suffering protagonist.)

   3--The hero extricates himself using HIS OWN SKILL, training or brawn.

   4--The mysteries remaining--one big one held over to this point will help
   grip interest--are cleared up in course of final conflict as hero takes the
   situation in hand.

   5--Final twist, a big surprise, (This can be the villain turning out to be
   the unexpected person, having the "Treasure" be a dud, etc.)

   6--The snapper, the punch line to end it.

   HAS: The SUSPENSE held out to the last line? The MENACE held out to the last?
   Everything been explained? It all happen logically? Is the Punch Line enough
   to leave the reader with that WARM FEELING? Did God kill the villain? Or the
   hero?

* Michael Moorcock
** How to write a novel in 3-days
   - First of all, it’s vital to have everything prepared. Whilst you will be
     actually writing the thing in three days, you’ll need a day or two of
     set-up first. If it’s not all set up, you’ll fail.

   - Model the basic plot on the Maltese Falcon (or the Holy Grail — the Quest
     theme, basically). In the Falcon, a lot of people are after the same thing,
     the Black Bird. In the Mort D’Arthur, again a lot of people are after the same
     thing, the Holy Grail. It’s the same formula for westerns, too. Everyone’s
     after the same thing. The gold of El Dorado. Whatever.

   - The formula depends on the sense of a human being up against superhuman force
     — politics, Big Business, supernatural evil, &c. The hero is fallible, and
     doesn’t want to be mixed up with the forces. He’s always about to walk out
     when something grabs him and involves him on a personal level.

   - You’ll need to make lists of things you’ll use.

   - Prepare an event for every four pages.

   - Do a list of coherent images. So you think, right, Stormbringer: swords,
     shields, horns, and so on.

   - Prepare a complete structure. Not a plot, exactly, but a structure where the
     demands were clear. Know what narrative problems you have to solve at every
     point. Write solutions at white heat, through inspiration: really, it can just
     be looking around the room, looking at ordinary objects, and turning them into
     what you need. A mirror can become a mirror that absorbs the souls of the
     damned.

   - Prepare a list of images that are purely fantastic, deliberate paradoxes say,
     that fit within the sort of thing you’re writing. The City of Screaming
     Statues, things like that. You just write a list of them so you’ve got them
     there when you need them. Again, they have to cohere, have the right
     resonances, one with the other.

   - The imagery comes before the action, because the action’s actually
     unimportant. An object to be obtained — limited time to obtain it. It’s easily
     developed, once you work the structure out.

   - Time is the important element in any action adventure story. In fact, you get
     the action and adventure out of the element of time. It’s a classic formula:
     “We’ve only got six days to save the world!” Immediately you’ve set the reader
     up with a structure: there are only six days, then five, then four and
     finally, in the classic formula anyway, there’s only 26 seconds to save the
     world! Will they make it in time?

   - The whole reason you plan everything beforehand is so that when you hit a
     snag, a desperate moment, you’ve actually got something there on your desk
     that tells you what to do.

   - Once you’ve started, you keep it rolling. You can’t afford to have anything
     stop it. Unplug the phone and the internet, lock everyone out of the house.

   - You start off with a mystery. Every time you reveal a bit of it, you have to
     do something else to increase it. A good detective story will have the same
     thing. “My God, so that’s why Lady Carruthers’s butler Jenkins was peering at
     the keyhole that evening. But where
   was Mrs. Jenkins?”

   - In your lists, in the imagery and so on, there will be mysteries that you
     haven’t explained to yourself. The point is, you put in the mystery, it
     doesn’t matter what it is. It may not be the great truth that you’re going to
     reveal at the end of the book. You just think, I’ll put this in here because I
     might need it later. You can’t put in loads of boring exposition about
     something you have no idea of yourself.

   - Divide your total 60,000 words into four sections, 15,000 words apiece. Divide
     each into six chapters. You can scale this up or down as you like, of course,
     but you’ll need more days — and stamina — for longer books, and keep chapters
     at 2.5k max. In section one the hero will say, “There’s no way I can save the
     world in six days unless I start by…” Getting the first object of power, or
     reaching the mystic place, or finding the right sidekick, or whatever. That
     gives you an immediate goal, and an immediate time element, as well as an
     overriding time demand. With each section divided into six chapters, each
     chapter must then contain something which will move the action forward and
     contribute to that immediate goal.

   - Very often a chapter is something like: attack of the bandits —defeat of the
     bandits. Nothing particularly complex, but it’s another way you can achieve
     recognition: by making the structure of a chapter a miniature of the overall
     structure of the book, so everything feels coherent. The more you’re dealing
     with incoherence, with chaos — ie with speed — the more you need to underpin
     everything with simple logic and basic forms that will keep everything tight.
     Otherwise the thing just starts to spread out into muddle and abstraction.

   - So you don’t have any encounter without at least information coming out of it.
     In the simplest form, Elric has a fight and kills somebody, but as they die
     they tell him who kidnapped his wife. Again, it’s a question of economy.
     Everything has to have a narrative function.

   - Use the Lester Dent Master Plot Formula.  You must never have a revelation of something
     that wasn’t already established; so, you couldn’t unmask a murderer who wasn’t
     a character established already. All your main characters have to be in the
     first part. All you main themes and everything else has to be established in
     the first part, developed in the second and third, and resolved in the last
     part.

   - There’s always a sidekick to make the responses the hero isn’t allowed to
     make: to get frightened; to add a lighter note; to offset the hero’s morbid
     speeches, and so on. The hero has to supply the narrative dynamic, and
     therefore can’t have any common-sense. Any one of us in those circumstances
     would say, ‘What? Dragons? Demons? You’ve got to be joking!’ The hero has to
     be driven, and when people are driven, common sense disappears. You don’t want
     your reader to make common sense objections, you want them to go with the
     drive; but you’ve got to have somebody around who’ll act as a sort of chorus.

   - When in doubt, descend into a minor character. So when you reach an impasse,
     and you can’t move the action any further with your major character, switch to
     a minor character ‘s viewpoint, which will allow you to keep the narrative
     moving, and give you time to brew something.
** 7 Pillars of Moorcocks Method
   1. Plan and prepare before you start. Set up a few key things before the
      three-day ‘writeathon’: characters, settings, themes, possible plot
      developments.

   2. Make the basic plot of your novel the quest narrative (Moorcock uses the
      examples of The Maltese Falcon and the Grail Quest). Your hero/heroine and
      sidekick/helper etc. are looking for a particular item/person, but so are the
      bad guys. It’s a race against time to see who’ll get there first. (Here,
      we’re always reminded of the Indiana Jones films, which follow such a plot.)

   3. Make something happen every few pages, so the story is well-paced. Divide the
      action up into four sections and then divide those four sections up into six
      chapters. The idea is that you know that, by the end of each quarter, the
      plot has to have moved forward in a significant way. Moorcock also recommends
      that, at a more local level, each chapter directly moves the action forward.

   4. If it’s a fantasy or SF novel (Moorcock’s forte during his early career) that
      takes place in a different world, make a list of some images which embody
      that world and make it vivid: landmarks, objects, geographical features, etc.
      Then, when you write, you can just go to this list and fill in the picture
      for the reader. Make these vivid: elsewhere in his list, Moorcock suggests
      that ‘paradox’ is a good rule of thumb, e.g. ‘the City of Screaming Statues’.

   5. Prepare an overall structure. (This is not the same as a plot, Moorcock tells
      us – just the basic framework of the novel. You can fill in the gaps later.)

   6. Think about the timing of the story’s events: e.g. how long has the hero got
      to retrieve the Grail/save the world?

   7. Start off with a mystery – and then, every time you solve one mystery, that
      leads to, or creates, another. (An example might be: the hero needs to find
      someone who can help him in his quest. When he tracks down the person,
      they’ve already been killed – but there’s a clue on their person, such as a
      note or a map, that leads our hero on to his next challenge.)

** 10 Tips for Good Storytelling
   1. My first rule was given to me by T.H. White, author of The Sword in the Stone
      and other Arthurian fantasies and was: Read. Read everything you can lay hands
      on. I always advise people who want to write a fantasy or science fiction or
      romance to stop reading everything in those genres and start reading everything
      else from Bunyan to Byatt.

   2. Find an author you admire (mine was Conrad) and copy their plots and characters
      in order to tell your own story, just as people learn to draw and paint by
      copying the masters.

   3. Introduce your main characters and themes in the first third of your novel.

   4. If you are writing a plot-driven genre novel make sure all your major
      themes/plot elements are introduced in the first third, which you can call the
      introduction.

   5. Develop your themes and characters in your second third, the development.

   6. Resolve your themes, mysteries and so on in the final third, the resolution.

   7. For a good melodrama study the famous “Lester Dent master plot formula" which
      you can find online. It was written to show how to write a short story for the
      pulps, but can be adapted successfully for most stories of any length or genre.

   8. If possible have something going on while you have your characters delivering
      exposition or philosophising. This helps retain dramatic tension.

   9. Carrot and stick—have protagonists pursued (by an obsession or a villain) and
      pursuing (idea, object, person, mystery).

   10. Ignore all proferred rules and create your own, suitable for what you want to
       say.
