#+TITLE: The Story of V
#+STARTUP: indent

* How to write Flash Porn
+ [[https://gretachristina.typepad.com/greta_christinas_weblog/2007/10/how-i-write-por.html][Greta Christina]]
  How does it feel to be this person, or these people, having sex? How do these
  sex acts feel physically -- soft, tight, sharp, gentle, smooth, cold? 
  How do they feel emotionally – nervous, urgent, giddy, relieved, beloved, dirty?

  It has to convey what the sex means.  Why the people are having it. Whether
  it's giving them what they'd hoped for. What about it is surprising. Whether
  anything is going to be different now because of this sex.
+ [[http://terribleminds.com/ramble/2012/06/26/25-things-you-should-know-about-writing-sex/][Chuck Wendig]]
+ [[http://www.thereviewreview.net/publishing-tips/flash-fiction-whats-it-all-about][Flash Fiction What it's All About]]   
+ [[https://www.fanfiction.net/s/9661958/1/The-Ultimate-Guide-to-Writing-Smut-Fic][Smut Fiction]]
+ [[https://thewritepractice.com/dialogue-tags/][How to use Dialog tags]]
* Paragraph Template
- What emotions are the character feeling?
- Why are they doing what they are doing?
- How does the physical stimulation feel?
- What does the character think about the other character?
* Template
 - Story
  One-liner on what the story is about.
 
- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes
  Correspond to the plot.  This is the actual story.

* Mystery's to Solve
- Agent 99
  - Facts
    - V said they met only one time yet she has an email where she explains that
      she is dropping Artem off at the airport then heading back to her hotel.
      She gives him her number as says maybe they can hangout.
    - If she only met him one time then why the email.
  - Who is he?
  - Where did you meet?
- The Couch
  - Why fuck on the couch and not the bed?
  - V claims he wasn't special enough yet she was traveling with him and fucking
    his brains out.  How much more special do you need to be?
  - She claims that he wasn't special because at this point he violated her
    trust yet he was still special enough to fuck and travel with.
  - It doesn't make sense.

* Who is V?
- Who is V?
- What is her purpose in writing these stories?
  - Lessons learned to help other women.
  - Create a record of her sexual adventures.
- What makes her so sexual?
- She is no different than other women.
- She loves sex and is not afraid to admit it.
  
* Casual Encounters
** Agent 12
- Story
  V has an encounter with an oversized cock.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

* Old Men
** Sidetracked
- TODOS

  - TODO When V starts playing with herself Rick describes her body and why she
    is so sexy. See Delta of Venus "Pierre"

- Story V sucks dick on the side of the highway on the way to Vegas.

- Characters V - her usual horny self. Rick - Her current love interest.
  
- Plot
  - V and her lover have a conversation about sex. V and her lover are still in
    the honeymoon phase which means lots of fucking. V's lover asks where V has
    sucked dick in the past. V tells him in all sorts of places theater, parking
    lot, beach, car. V starts to rub her lovers cock, he has a hard time
    concentrating on driving. V's pussy is throbbing, she is thinking of sucking
    his cock while he drives. They are on the highway going to Vegas about 10
    miles outside of Barstow in the middle of nowhere.
  
  - V's proposes a roadside blowjob. V has a flashback to the year before
    sucking dick in a car. She tells her lover the story but doesn't say who it
    is. It's her previous lover who is also friends with her current lover. She
    thinks about how much better a fuck her former lover is. She asks him to
    pull over and begins to suck his dick.
  
  - V's sucks her lovers cock. She loves a hard cock in her mouth. She's been
    sucking dick since she was 16. She's never had a bad experience sucking
    dick. She loves how it makes her lover feel. She does it out of love.
 
I'm never surprised when I get the question, for some reason it always
comes up. How many men have you slept with? Have you ever been with a woman?
How do I compare to the others? By the way how many others have there been?
It's always the same question. In some ways it amuses me, they ask the
question then when you answer it they feel jealous or hurt. The best way to
answer such questions is with brutal honesty. Am I the best? Sorry, I've had
better. What better way to put them in their place. Oh and my favorite, what's
the biggest you've ever been with? As if I carry around a measuring tape for
such occasions.

To be honest you don't need a measuring tape, a woman knows a big one as soon
as its owner tries to ram it home. Why do men that are huge think they are
good lovers? I will admit one of the most exciting sights is when a "big" man
reveals his treasure. Feeling the weight of it in your hands, knowing that it
would take three or four average sized men to equal this one. Men with size
know they have to make sure the woman is ready, if not they run the risk of
scaring her off. There's nothing worse than a big cock trying to push into a
pussy that's not quite ready. I get extremely wet whenever a man strokes
himself in front of me. I ask them "Baby can you please get it wet and stroke
it for me." It doesn't take much to get a man to stroke
himself, especially in front of a woman who he intends to take. I instruct
them "Stroke it til you're about to cum, then I know you're ready." Sometimes
I will bend down and blow on him while he strokes it, or lay back with my legs
wide open so he can see his goal.

Rick is my fiance.  We were introduced by my previous lover who was 20 years
older than me.  Jim was a fantastic lover but I will save that for another story.
** Heat of The Night
- Story V sneaks off to get fucked from behind.

- Characters
  V - Is recently divorced and feeling low in confidence and self-esteem.  She
  needs a man to show her how desirable she is.  She is willing to do or try
  anything to prove herself.

  Jim - Is 20 years older than V and is a trained Kunf-fu master.  He also
  teaches Taoist lovemaking and has written a book about it.  He is a master
  lover and world-famous.  He's been brought in to make V feel like a woman.

- Plot
  - V has a strong desire to be with Jim so she sneaks off at night leaving her
    kids with her mom.
  - V really has a need for Jim's cock.  She wasn't able to cum their first time
    together because she was too nervous.

- Scenes
  - Scene 1: V is at home lying in bed but she can't sleep. She is torn with
    anxiety and desire because she wants to sneak off and be with Jim. She has
    unfinished business with him, she needs to cum.
    
  - Scene 2: It's late at night and Jim here's a knock at the door.  He's
    pleasantly surprised to find V standing there in a long coat.  Little does
    he know that underneath is just panties and no bra.

  - Scene 3: V tells Jim that he is the best and that she needs his hard cock.
    She promises to do whatever he wants as long as he makes her cum.  Jim
    smiles and asks her if that's really the deal she wants to make.  She
    answers yes.

  - Scene 4: Jim fucks V and gives her the best orgasm of her life.
** The Great Escape
- Story
  V finds time to fuck her lover while visitors are in the house.

- Characters
  V - her usual horny self.
  Jim - V's lover, professional sex instructor, and 20 years older.
  Rick - Jim's friend and potential fuck-interest for V.
  Matt - Another visitor.

- Plot (four scenes ~ 375 words per scene)
  - V's boyfriends friends are vising for the week.
    - She pictures herself fucking one of the friends.
    - She wonders who has the bigger dick.
  - V hasn't fucked her boyfriend in two days.
    - She touches herself in the bathroom.
    - She tells her boyfriend how much she wants to fuck him.
    - She offers her boyfriend a threesome.
  - V doesn't care who's in the house she is going to fuck her boyfriend.
    - V decides to fuck her boyfriend.
    - V makes out with her boyfriend while one of his friends watches.
    - V's boyfriend fingers her while his friend watches.
    - V's boyfriend fingers her in the kitchen.
  - V fucks the shit out of him.  Probably the wildest fuck yet.
    - V's boyfriend eats her pussy from behind.
    - V gives her boyfriend a prostrate massage while milking his cock.
    - The house guests hear whats going on.

- Scenes
  
** I Spy
- Story
  V is in Thailand with her much older lover. - She doesn't know it but her
  lover has arranged for a spy to watch their every move in the bedroom.

- Characters
  V - Recently divorced V is discovering her true sexuality and loving it.  She
  has learned things that she could never have learned with her ex-husband.
 
  Jim - 20 years older than V, Jim is showing her the best way to be a slut.

  Ron - One of the hidden friends.

  Matt - One of the hidden friends.

- Plot
  - Jim has been training all day and finally finds time for V.  Jim has
    promised her some special "desserts" on this trip and he plans to deliver.
    He knows the best thing is to let V's anticipation build.

  - V is in a very high state of sexual awareness.  It's her first time in Thailand and
    her senses are overloaded.  V is learning how to be more assertive and enjoy
    her sexual experiences.
 
- Scenes
  - Scene 1: V and Jim have a conversation about sexual acts that may not be
    considered normal.

  - Scene 2: During the conversation Jim takes out his cock and starts to rub
    it.  V immediately drops to her knees but Jim stops her.  He wants to teach
    her to be patient and build anticipation.  He finally lets her suck his
    dick.

  - Scene 3: In the meantime unknown to V two of Jim's friends are hiding in the
    closet.  This is one of the "desserts" he has promised her.  In previous
    conversations Jim told his friends how raw V is and that with a little
    "molding" he could turn her into a world-class slut.  The agree to help.

  - Scene 4: V and Jim start to fuck.  About 30 minutes into the session Jim's
    friend make themselves known based on a pre-arranged signal.  V is surprised
    and a little scared but watching the two men stroke their big cocks has made
    her forget her fear.  Jim promises that all they will do is watch.
** The Big Apple
- Story
  V says goodby to her old man in style

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** What Happens in Vegas Stays in Vegas
- Story
  V fucks multiple lovers in Vegas.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** On The Road Again
- Story
  V takes a trip with her old-man and gets fucked in a trailer.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

* Higher Learning
** Lick It Up
- Story
  V's college boyfriend helps her see the light with his active tongue.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Dogs and Cats
- Story
  V wakes up to her pussy being eaten and get a big surprise.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Three's Company
- Story
  V is surprised by a second cock pushing into her from behind.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

