#+TITLE: Story of V
#+STARTUP: indent

* How to write Flash Porn
+ [[https://gretachristina.typepad.com/greta_christinas_weblog/2007/10/how-i-write-por.html][Greta Christina]]
  How does it feel to be this person, or these people, having sex? How do these
  sex acts feel physically -- soft, tight, sharp, gentle, smooth, cold? 
  How do they feel emotionally – nervous, urgent, giddy, relieved, beloved, dirty?

  It has to convey what the sex means.  Why the people are having it. Whether
  it's giving them what they'd hoped for. What about it is surprising. Whether
  anything is going to be different now because of this sex.
+ [[http://terribleminds.com/ramble/2012/06/26/25-things-you-should-know-about-writing-sex/][Chuck Wendig]]
+ [[http://www.thereviewreview.net/publishing-tips/flash-fiction-whats-it-all-about][Flash Fiction What it's All About]]   
+ [[https://www.fanfiction.net/s/9661958/1/The-Ultimate-Guide-to-Writing-Smut-Fic][Smut Fiction]]
+ [[https://thewritepractice.com/dialogue-tags/][How to use Dialog tags]]
* Templates
** Story Template
 - Story
  One-liner on what the story is about.
 
- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes
  Correspond to the plot.  This is the actual story.
** CASE: Template
*** Case
*** Testimony
*** RFIs
*** Conclusions and Speculations

** Paragraph Template
- What emotions are the character feeling?
- Why are they doing what they are doing?
- How does the physical stimulation feel?
- What does the character think about the other character?

* Unsolved Mysteries
** CASE: 110812 MP
*** Case
V claims to have met Matt at the airport and helped with his luggage.

*** Testimony
- Email dated 12 August 2011:
  Hi, there,
  It looks like I'll be at Viktoria station at about 1 p.m ( hopefully). My
  plane will arrive at about 11:25 local time and I need to drop Junior off in
  Gatwick. Then I'll take a train to Viktoria. Just in case my # +372 5958 4578. 
  Hope to see U tomorrow. Keep in touch . 

  V

- V said they met only one time yet she has an email where she explains she will
  be "landing".  This suggest she met him on a previous trip.  She goes on to
  say she hopes to see him the next day.  For example if she only had one
  interaction with him at the airport that email suggest a second interaction. 
- A Google search reveals that Matt lives in Chicago and is a soccer coach.
- V claims they met the baggage claim in London and that her and Anna helped
  him with his luggage.  That was the only contact she ever had with him.
- Tom accused V of having an affair with him.  

- 190711 UPDATE
  When confronted with the email proof of her attempted contact V got nervous
  and started tap dancing.  First she said that she was simply meeting him
  because he was someone she knew in London.  Then she said he was a fb friend
  (He is not) she kept trying to explain why she was friends with him even
  though she only met him "once." I think there is more to the story.

*** RFIs
- If she only met him once then why does she have an email saying she will meet
  him or hangout?
- Why does the old-man think she had an affair with him?
- How does the old-man even know about him?
- When did V experience her 12, before or after her divorce?
- Is Matt Agent 12? V claims to have experienced 12 just one time.

*** Conclusions and Speculations
- She had to have met him more than once, especially if there's an email.  
- It's almost as if she met him on one trip, then on a subsequent trip she emails him
  and says she will be in town let's hang out.  Strange.
- I suspect the old-man found out while snooping her emails.
- Or maybe she told him during an argument.
- I assumed V met MP in 2012, but if the Tom accused her of being with him
  there's no way that could be.  In August 2012 her and Tom would have been over
  because RC proposed in July 2012.  This means V would have met MP on a
  previous trip to London.
- I believe V met MP in May 2011 when she attended the Chelsea Flower Show.

** CASE: 140420 Tims69
*** Summary
- I discovered V was communicating with tims69 via email.
- This was in April 2014 around Easter time four months after we got together.
- She sent him pics of things she was doing with me.
- I didn't like it.

*** Testimony
- V claims it was someone from CA that she met when she was there for her ill
  fated marriage.
- I don't believe her because the emails seemed to indicate they never met face
  to face.  The tone of the emails suggested they were getting to know each
  other.
- V they exchanged between 10-12 emails, around Easter time in 2014.
- V sent him pics of some of our outings together.

*** RFIs
- Why did V feel the need to correspond with this person?
- Where did she really meet him?
- Was she playing the field and using him as a possible safety net?
- How did they meet? Dating site? Or was she telling the truth.

*** Conclusions and Speculation
- I think V was trying to play both sides just in case one side, mainly me,
  didn't work out.
- I suspect they mat on RoseBrides.com.
- Google search does not show anything meaningful.
  
** CASE: The Newsletter
*** TODO confirm the timeline of the newsletter visit and actual visit.

*** Summary
V sent me a newsletter that seems to indicate Tom visited Odessa in 2009 which
is before their first meeting June in 2010.


*** Testimony
- Tom mentions a woman that picked him up from the airport and delivered
  him to his accommodations.  He says he was picked up his friends wife's gf.
  I believe the friends wife he's talking about is Lori.  If that's the case
  then it suggest that Yuri and Lori were not present the first time Tom met V.
  The problem with that theory is he says that V tells Lori all about him
  although there's nothing to indicate that that conversation was in person.
  V could have discussed him over the phone and word got back to Tom.  If that's
  the case then their first meeting was without Yuri AND this may have been the
  setup. 

- V said that the first time she met Tom Yuri and Lori were also in Odesa
  although I may have misheard her.  Tom's NL testimony does not support V's
  testimony, although her testimony may apply to the June 2010 visit.

- He also says that she came back at around 19:00 and stayed to the early
  morning just talking.  she admits that she read his book and says "I'm
  convinced you are the best."
- The following morning she tells her friend (Angela or Lori) all about it.
- Tom was there to see Konstantin, who by the way, was mentioned in
  another email the context of which was "free love" or "anything goes."

*** RFIs
- Is the timeline correct? V doesn't deny the story but she does deny the
  timeline.
- If she did meet him before the setup did they fuck?
- If they did meet was Lori and Yuri aware of it? They had to be.  They would
  have been the one's to ask V to pick him up.

*** Conclusions and Speculation
- V is the woman in the story.
- There's no way Lori and Yuri would not say something to V about his visit.
- I wouldn't be surprised if they were the one's who arranged for her to pick
  him up at the airport.  After all she speaks very good English.
- If the timeline is correct this means that V met Tom well before the
  setup. 
- By my count Tom has visited Odessa at least three times.  Once for the
  setup, once with his friends, and once for the newsletter.
  UPDATE In another newsletter Tom claims to have visited Odesa in 2009, 2010,
  2013, and 2014.  2009 has the least evidence of a visit other than what's in
  the newsletter.  The other visits have been documented by V's photos or actual
  stories about the visit.

*** Update
- V admits to introducing Tom to Konstantin but the question is why? Did she
  know Konstantin was into martial arts? 

** CASE: The Lawyer
*** Case
- Tom says that one of the reasons why he never married V was because of
  some lawyer she had a relationship with.
- He seems to imply she had an affair.

*** Testimony
- V claims she had coffee with a lawyer.
- V claims the lawyer was a local.
- V says she told Tom about the lawyer but I don't remember the reason
  why.  I think she said she was trying to make him jealous.
- V did mention an immigration lawyer in CA but that was after Tom.

*** RFIs
- How did Tom find out about the lawyer?
- Does she still see the lawyer?
- Is he in Odessa?
- Is he an acquaintance or customer?
- Did he know H1?
 
*** Conclusions and Hypothesis
- Based on some recent testimony see CASE: Agent 12 it seems V had an affair
  with the lawyer.  I suspect he was a customer.
- Agent 12 is a local.
- Agent 12 is most likely a customer or an acquaintance.
- V seems to have a history of meeting other men while she is in a relationship.
  - Massimo when she was married to H1.
  - MP and the Lawyer while she was with Tom.
  - Tims69 with me.

** Case: Agent 12
*** Case
- V claims to have been with 12 inch cock

*** Testimony
- She said she was with a 12 inch cock.
- One time
- Limited to missionary
- Said it hurt
- Said she sucked it 
- She claimed it was Tom but I don't think it was not based on the testimony
  given above.
- 20190704 
  V now says Agent 12 was a local. It was someone she didn't expect to have sex
  with which means she knew him either as a friend or customer. when asked if it
  was one of her customers she said the doesn't remember. Clearly it was one of
  her customers. She also said it was after her divorce. I'm thinking it was the
  lawyer, after all Tom claimed she cheated on him with a lawyer and she admits
  to having "coffee" with one.  V said she also let him titty fuck her and she
  stroked his big cock.

  V also claims he wasn't married although I'd say there's a 5050 chance he was.
  V claims she did not fuck him at the apartment.
  This might be how Cialis knows her because of the lawyer.  I suspect Yanna or
  Angela may know him as well.
  V said he called her again but she didn't go on another date.

  I made a joke once and said that I might interview one of her former lovers
  and she said "maybe".  The lawyer could be that person.  He must be somewhat prominent.

*** RFIs
- Was this before her divorce or after? After
- Is he still her customer?
- If not a customer does she still run into him?

*** Conclusions and Speculation
- I suspect it may have been Matt Pearson.
- I don't think it was 12 inches.  She exaggerates.
  
** Case: Chechen
*** Case
- V claims to have dated a Muslim man.

*** Testimony
- V made comments about being in a relationship with a Muslim man.
- She seemed to indicate that he was overbearing.

*** RFIs
- Who is he?
- Is he still in Odessa?
- What country is he from?

*** Conclusions and Speculation
- I assume it was after her divorce.

** CASE: 120704 July 2012 Newsletter
*** Case
- Tom writes that "two friends betrayed him"
- Tom plans a trip to Odessa in OCtober 2012 the same month V is married.

*** Testimony
- V claims there was no betrayal.
- V says that Tom did not attend the wedding.

*** RFIs
- Is it possible he wanted to goto Odesa to win back V?
- Did he actually goto Odesa?
- Did V start a relationship before she ended the one with Tom?
- Did he try to get Yuri to intervene?

*** Conclusions and Speculations
- Betrayal suggest V cheated while she was still with Tom.
- In the newsletter Tom is in Russia.  He sounds like he is there to speak to
  Yuri about the situation.  He seems to be reflecting on what's going on.

** CASE: 1201dd Last Dance
*** Case
- V claims she never cheated on Tom with RC, there was no overlap.

*** Testimony
- V claims there was no overlap between Tom and RC.
- V claims stopped in NY on her way back to Odesa, after visiting in CA.
- V claims she stayed at Ron McNulty's place and that he wasn't there at the
  time.
- V claims that Tom arranged for her to stay there BEFORE she went to CA.
- V said that Tom met her in NY and she slept with him one last time
*** RFIs
- When was she in NY?

*** Conclusions and Speculations
- V was active with Tom up until Feb 2012 when he visited her.  There's a
  picture with Dima and Tom dated Feb 2012.  After Feb there seems to be no
  connection between the two.
- There's a pic of V and RC in a restaraunt dated Jun 2012 for her birthday.
- This is confusing because RC proposed in July, which is also when Tom was in
  Russia.
- So when did V have an opportunity to meet Tom in NY for their last dance?
- Is it possible that V met with Tom before she visited CA?
- What if this was a planned meetup with Tom before he went to Russia.  She
  meets him in NY in June BEFORE she goes to CA.  She tells him it's over, he
  asks if she is planning on seeing RC, she says yes.  Tom goes to Russia.
- Could this be the first time she's meeting RC in CA? I don't think so because
  he wouldn't ask her to marry him if this was her first visit.

*** Case Closed
  
** CASE: 111205 A Christmas Story
*** Case
- When did V betray Tom and what exactly did he mean by betrayal?
- V met RC in Oct 2011 and one year later they were married in Odesa.
- V had to have some physical contact with RC between Oct 2011 and Oct 2012.
- The only known record of contact was when she met with him Jun/Jul 2012.  That
  could not have been the first physical contact because he proposed in
  Jul 2012.
- V claims the itinerary was used to get her Visa.  The problem is that's not a
  requirement.  Why would a country use that as proof when they haven't even
  granted a Visa? I remember one year she tried to use the same trick going to
  England but in that case it was a hotel reservation which makes more sense.
  Typically there is no cancellation fee and the point is to show the authorities
  you have a place to stay.
  
*** Testimony
- V said she had no overlap between Tom and RC.
- There is an itinerary that shows V traveling to JFK from Warsaw dated 15
  Dec 2011.  Her return flight JFK to Warsaw on 27 Dec.  12 days in NYC.
- There's no indication that she flew from NYC to CA although it could be
  possible.
- V vehemently denies spending Christmas in NYC or the states in general.
  At one point I suggested she was there with RC and she actually stopped and
  thought about it but then said it was "too soon" or something to that
  effect.  I believe she was there to see RC.  How could you forget being some
  place for 12 days? I don't buy it.  She was there cheating on Tom, then goes
  straight back there 11 days later to be with him and at the end tell him
  it's over.Not cool. She said something along the lines that how could she be
  in NYC in DEC then turn around and visit Tom in CA.  She implied that she
  was not an Oligarch.  I replied that maybe someone paid for your ticket. 
- V said that even if she went to NYC who would she stay with, again
  entertaining the possibility that it might've happened.  That's she could
  have stayed with Tanya or it was paid for by RC.
- V also made the argument that she had kids and would not be away from them.
  That too is bs because she had no problem leaving them alone to sleep with
  Tom. 

*** RFIs
- Who did V stay with?
- Who was she seeing?
- Did she stay in NYC?
- If not where did she go? CA?

*** Conclusions and Speculations
- V had to have visited RC during this time.  This was the only time she could have sealed the
  deal.  Their next meeting wasn't til June/July when he proposed.  There's no
  way they could have established a physical relationship the same month he
  proposed.  There are no other documented meetings between the two.  Dec 2011
  had to be it.
- I believe she stayed with Tanya.

*** Case Closed
- V's vehement denial suggest she is hiding something.  
- She returned to CA in Jan to be with Tom AND this is also the time she stayed
  in Rick McNulty's place in NYC.  See CASE: Last Dance. 

** CASE: Overlap 
*** Case
- I believe there was some overlap between Tom and RC.
*** Testimony
- V went on a "date" with RC when Tom got sick.
- Tom stayed in the room, called RC and asked him to take V to get him (Tom) something to eat.
- RC picked her up, they went out to eat but the restaurant wasn't good so they went to McDs.
- They ate in a park and forgot all about Tom.
- He was mad.
- This took place AFTER their visit to Odesa.
* Secrets
- Roadside blowjob.
- Outdoor sex.
- Prostrate massage.
- Overlapping partners.
- Infidelity.
- Had a porn sized dick.

- Taught a sex class in Thailand.
- Demonstrator for a sex class.
- Watched Tom with another woman.
- Someone watched her while she had sex.

* Timeline
** 2009
- In Tom's Oct 2018 NL he mentions that fact that his first visit to Odesa was
  in 2009.  He states that a friend of a friend picked him up at the airport (V).
  Later that night around 7 pm she knocks on his door and they spend all night
  drinking wine and talking, she tells him she read his book and said "I'm
  convinced you're the best." The following day she talks about him with her
  friend (Angela).
- Tom was visiting Konstantin and Artem for training.
- I'm sure the woman who picked him up is V.
- Why? She speaks good English and Yuri would have told her of Tom's visit.  V
  claims Tom is mistaken about the year but does not deny the story.  Is it
  possible she started a relationship with him in 2009? Which begs to question
  was his visit in 2010 setup by Yuri or did V ask for the setup?
- In that same NL Tom claims to have visited Odesa in 2009, 2010, 2012,
  and 2014.

** 2010
- March
  - V is divorced from #1.

- June
  - Tom arrives in Odesa to take care of V.  Did V ask for the visit based on
    her contact with him in 2009, or did Yuri set it up.

- July
  - V and Tom are in Paris together.  V claims he wasn't invited and just showed
    up but that didn't stop her from having fun with him.  She made it sound
    like she didn't want him there but I think that's BS.  They just started
    their relationship (supposedly) in June which means she was still in love
    with him.  Plus she is with him in Istanbul looking very happy.

- October
  - V and Tom vacation in Istanbul.
  - Tom is also training two students while they are in Istanbul.  Who were the students?

- November

** 2011
- January
  - 08 V is in Sofia Bulgaria skiing.

- February
  - 14-19 Islanda Village Resort.  V claims to have made the reservation but
    then canceled it when she learned she had to take a boat to the island.
  - V and Tom vacation in Thailand.  V claims to have had a separate room while
    in Bangkok but one room when they went to the resort.  I don't buy it.

- May
  - V is in London for the Chelsea Flower Show.
  - I believe this is when she meets MP.  V states that Ana was with her when
    they met MP.  She said she helped him with his bags, which is odd.  I've
    traveled all over and have never needed help with my bags.  I wonder if Ana
    remembers him? I remember in one of V's emails her talking about the size of
    "Matt's" cock.  Which Matt was she talking about?  

- August 
  - 11 V is in Paris with the kids.
  - 12 V meets MP in London.  
  - 21 V is in London with both kids.

- October
  - Tom and RC visit Odesa.  V's first time meeting with RC.
  - 1 year later V and RC are married in Odesa.  V claims there was no overlap
    between Tom and RC although I'm sure there was some "emotional" overlap.  In
    other words there may not have been any physical contact but surely the
    "flame" was ignited while she was still with Tom.  This is just as bad or worse.

- November
  - Tom is still in Odesa.
  - I believe at this point V starts communicating with RC. This is the
    beginning of the end for Tom.

- December
  - 15 Warsaw to JFK
  - 27 JFK to Warsaw
  - 28 Warsaw to Odesa
  - Three days later she is Moscow.
  - In less than two weeks (11 days) she is heading back to the states to CA.
  - No other flights indicated.  It looks like she stayed in NYC for 12 days.
  - Is it possible she met Rick on NYC? This would make sense and answer the
    question regarding the betrayal.  If this is true then there is overlap, no
    question about it.
  - Scenario 1: She meets RC in NYC where they seal the deal.

  - UPDATE
    V claims to have made the reservation so she could get her Visa to visit
    Tom.  She cancels the reservation.
    There's a picture of her and Artem on a plane going to Moscow dated 27
    December which means she is probably telling the truth about the fake reservation.

** 2012
- January
  - 01 V is still in Moscow.
  - 17 JFK-LAX 
  - 30 LAX-JFK
  - 2012.01.29 V is in CA with Tom.  They visit Hotel Coronado.  Confirmed with
    a fb post of three pics of the hotel.

  - I also believe this is when the last dance took place.  They flew from CA to
    NY but it's possible she didn't end it right then.
  - Opportunity #1 to end it.
  - Did she seal the deal with RC during this visit? She would have had
    to sneak around.
 
- February
  
 
- March
  - Tom's January 2012 Newsletter indicates he will be in Vegas in March.  

- April
  - Tom's May NL indicates he is in CA.

- May
  - 1-6 May Tom is in Vietnam (May 2015).  I recall V writing a letter about his
    trip to Vietnam saying how proud she was of him.  Could she still be with him?
  - Tom writes about heartbreak in this NL.  If he is writing about "his"
    heartbreak then she would have ended it in January or February maybe while they are in NY
    on their way back to Odesa.  
  - Why did it take so long for him to write about it? When did he find out? Is
    it possible she didn't tell him in Jan/Feb? Maybe she was waiting to seal
    the deal with RC.
  - 30 Tom is in Odesa.  
  - Opportunity #3 to end it.

- June
  - 3 Tom leaves Odesa (May 2015 NL).
  - 4-17 Tom is in Russia (May 2015 NL).
  - 18-28 Tom returns to Odesa.  This makes sense V's birthday is on the 19th
    (May 2015 NL). It seems to be V would have left for CA by now, which means
    Tom was in Odesa without her.
  - 20 V is in CA with RC celebrating her birthday. 
  - Betrayal?
  - Is V still with Tom during this time? The dates don't seem to support this
    as being the last dance. 
  - It looks like the only time V would have had an opportunity to be with RC is
    in January.  V has no documented trips between Jan and Jun.  

- July
  - 23 Odesa to Istanbul
  - 23 Istanbul to LAX
  - 26 LAX to Istanbul
  - 27 Istanbul to Odesa
  - 04 Rick proposes.
  - Tom is in Russia sulking contemplates another Odesa visit.
  - 2012.05.16-31 Johannesburg S. Africa.

- August
  - V takes Artem to English camp.  She emails MP and tells him she will be
    in London and that they should hangout.  If she only met him once then why
    is she talking about her plane landing? Something is suspicious.  Tom claims
    she cheated on him so it had to have happened before 2012.
  - 13-20 Tom is in NY (May 2015 NL)
  - 25 V is on a yachting trip in Odesa.

- October
  - V is married to RC in Odesa.
  - 6-23 Tom is in CA (Jul 2012 NL)
  - 2-17 Tom is in CA (May 2015 NL)
  - 19 V posts on fb that she is engaged.
  - 22 V is on her honeymoon in Israel.

- November
  - 28 V celebrates Artem's birthday with RC over Skype.

- December
  - 29 V is in Moscow with Lori.
  - Tom's December NL announces V and RC's engagement and says they met in 2011.

** 2013
- January
  - 14 ODS-IST
  - 14 IST-LAX
  - 27 LAX-IST
  - 28 IST-ODS
  - V is in CA for RC's birthday.

- February
  - 14 V and RC goto Vegas.
  - 26 V is in CA.
  - Ana is hurt while skiing with Dima.  V is still in CA.

- June
  - 13 V is in CA.
  
- September
  - V meets Vince two days before she leaves for CA.
  - V and kids go surfing.
  - V goes to CA and is officially married.

- October
  - V returns to Odesa her California dream shattered.

- December
  - 24 V sees Vince.

** 2014
- January
  - 06 V seals the deal with Vince.

- April
  - V is sending emails to tims69.  Note Vince learns about the letters in
    August when he snoops V's emails.

- August
  - Vince snoops V's emails and learns all kinds of good stuff.
    
** 2018
  - 2018.10 Tom's October NL indicates he was in Odessa in 2014.  I believe Tori
    got her facetime call that year.  Maybe it was around October or November.

* Weird shit V believes
- V believes if she gets naked in front of a man, the man will not think about
  fucking her.
- V believes that a microwave heats the container for example the dish or bowl
  instead of the food. 
- V said that one hour of swimming was enough to flatten her belly.
- "Bugs are bugs, and bees are bees"

* Who is V?
- Who is V?
  1. Does not like confrontation.
  2. Likes it when she is not challenged.
  3. Tries to misdirect or change subject when uncomfortable.
  4. Forgetful.  She may not lie, but she definitely forgets.  Keep this in
     mind when questioning her.
  5. Doesn't mind going on separate vacations.
  6. Likes to stroke ego and sugarcoat.
  7. Will do things to make others happy at the expense of her own happiness.
  8. Overly enthusiastic which sometimes clouds her judgement.
  9. Impressed by everything. 
    
- What makes her sexual?
  - Likes to fuck.
  - Prefers to cum PIV.
  - Prefers oral as warm up not main event.
  - Has tried anal.
  - Wide range of experiences.
  - Too many partners to remember.
  - Wrote a sex manual.
  - She loves sex and is not afraid to admit it.
  
* Casual Encounters
** Agent 12
V has an encounter with an oversized cock.

- Plot
  - V emails Mr. Big telling him she will be in London for a week and wants to
    know if they can hangout.
  - Mr. Big replies he is available and remembers their first encounter
    together.  He strokes his massive cock until he cums.
  - V gets rid of her kids and waits for Mr. Big to arrive at her hotel room.
    When she opens the door he immediately grabs her and gives her a passionate
    kiss.
  - Mr. Big asks her if she remembers what happened the first time they met.
    She, does and asks if she can do more to his huge cock than touch it.
  - Mr. Big responds by fucking her although getting into her tight pussy is
    hard at first, afterwards V goes animal on him.  She wonders how she can
    fuck a smaller cock after Big's dick has been in her.

- Characters
  V - She is away on vacation with her kids but it doesn't stop her from
  continuing her adventures.
  Mr. Big - V emails Mr. Big who she met on a previous trip and tells him she
  will be in London for a week.  Mr. Big remembers when they first met although
  he didn't fuck her then, he gets signals from her that she is ready.  During
  that first meeting he shows her his cock and she touches it but nothing else
  happens.  They were drunk. 

- Story

** Have a Taste
V's husband wakes up and finds V's best friend in a state of undress.

- Plot
  - V's friend tell her husband that she hasn't had a man in many years.
  - V told her it was ok if he had a taste but was not to fuck her or get his dicked sucked.
  - V's husband eats her friends pussy and brings her to a very loud orgasm.
  - Neither one of them knows that V is watching from the doorway.
  - Afterwards V rewards her husband with a very wild dick sucking.

- Characters

- Story
  V's husband wakes in the middle of the night and is invited to taste her best friend.

"It's ok, if you can get him to do it I don't mind" V said.

I feel sorry for her V thought.  To not know a man's touch, or any touch for
that matter is a crime against nature.  How could she go so long?

My husband is adequate when it comes to oral pleasure, my previous lover known
as Tom was much better, but I love my husband and am obligated to give
him an above average rating in this area.  Ahhh, but Tom, I'm getting
wet thinking about his tongue between my legs.  I have never gotten so much
pleasure from one man.  He was absolutely perfect in every way, especially for
someone his age.
* Tom
** Heat of The Night
V sneaks off in the middle of the night to get fucked from behind. V has a
strong desire to be with Tom so she sneaks off at night leaving her kids
with her mom. V really has a need for Tom's cock. She wasn't able to cum
their first time together because she was too nervous.

- Characters
  V - Is recently divorced and feeling low in confidence and self-esteem.  She
  needs a man to show her how desirable she is.  She is willing to do or try
  anything to prove herself.

  Tom - Is 20 years older than V and is a trained Kunf-fu master.  He also
  teaches Taoist lovemaking and has written a book about it.  He is a master
  lover and world-famous.  He's been brought in to make V feel like a woman.

- Story
  - Scene 1: V is at home lying in bed but she can't sleep. She is torn with
    anxiety and desire because she wants to sneak off and be with Tom. She has
    unfinished business with him, she needs to cum.
    
  - Scene 2: It's late at night and Tom here's a knock at the door.  He's
    pleasantly surprised to find V standing there in a long coat.  Little does
    he know that underneath is just panties and no bra.

  - Scene 3: V tells Tom that he is the best and that she needs his hard cock.
    She promises to do whatever he wants as long as he makes her cum.  Tom
    smiles and asks her if that's really the deal she wants to make.  She
    answers yes.

  - Scene 4: Tom fucks V and gives her the best orgasm of her life.

** The Great Escape
V's old-man is visiting with some of his Kung Fu students. Although V is happy
to host them she is disappointed that she won't be able to fuck Tom
whenever she wants.  

- Characters
  V - In a new relationship V is excited to explore areas of her sexuality she
  didn't know existed.
  Tom - V's lover, professional sex instructor, and 20 years older.
  Rick - Tom's friend and potential fuck-interest for V.
  Matt - Another visitor.

- Story (four scenes ~ 375 words per scene)
  - V's boyfriends friends are vising for the week.
    - She pictures herself fucking one of the friends.
    - She wonders who has the bigger dick.
  - V hasn't fucked her boyfriend in two days.
    - She touches herself in the bathroom.
    - She tells her boyfriend how much she wants to fuck him.
    - She offers her boyfriend a threesome.
  - V doesn't care who's in the house she is going to fuck her boyfriend.
    - V decides to fuck her boyfriend.
    - V makes out with her boyfriend while one of his friends watches.
    - V's boyfriend fingers her while his friend watches.
    - V's boyfriend fingers her in the kitchen.
  - V fucks the shit out of him.  Probably the wildest fuck yet.
    - V's boyfriend eats her pussy from behind.
    - V gives her boyfriend a prostrate massage while milking his cock.
    - The house guests hear whats going on.

"V I'd like you to meet two of my favorite students, this is Rick and this is
Matt" Tom said.

"Hi, my name is V." I said extending my hand.

Matt was a little to young for me.  After being with my first husband and Tom
I've come to prefer older more experienced men.  On the other hand Rick was just
my type.  As a physical specimen he wasn't that impressive but the one thing
that caught my interest is he wasn't married.  
** I Spy
- Plot
  - V has been waiting all day and is angry because of it.  
  - Tom has been teaching all day and is ready to fuck but he also has a surprise
    for V.  
  - Tom has arranged for two of his students to walk-in on them in their hotel room while
    they are fucking.  The idea is to further develop V's sluttiness and at some
    point introduce her to group sex.  
  - Because of her anger V is unusually aggressive in bed and discovers a new side
    to her sexuality which is sometimes she needs to fuck with abandon.

- Characters
  V - Recently divorced V is discovering her true sexuality and loving it.  She
  has learned things that she could never have learned with her ex-husband.

  Tom - 20 years older than V, Tom is showing her the best way to be a slut.

  Ron - One of the hidden friends.

  Matt - One of the hidden friends.
 
- Story
   
** The Big Apple
V says goodby to her old man in style.  In V's mind Tom is the best fuck she's
ever had, and may be the best she will ever have so she decides to give up her
pussy one more time.

- Characters
  V - V has decided to give up on Tom because he refuses to leave his wife.  She
  has her sights set on Tom's friend but has not give him a ride yet.  Before
  she drops Tom she plans to show her appreciation for all good fuckings he's
  given her.
  
  Tom - Tom knows V is not happy with him.  His age difference and the fact that
  he will not divorce his wife are two factors she cannot overcome.  He also
  knows that he is the best fuck she's ever had and most likely will ever have.
  He plans to give her the best going away she's ever had.

- Scenes
  - V tells Tom it's over.  Tom understands and ask that he spend one more night
    fucking her.  V is turned on and agrees/

  - Tom shares some special techniques with V and makes her cum several times.
  
  - V is torn between dumping Tom, how can she give up such good fucking.

  - V tells Tom she plans on dating Rick.  Tom understands and tells her about
    Rick's techniques. 
** What Happens in Vegas Stays in Vegas
- Story
  V visits Vegas for the first time and shows her appreciation.

- Characters
  V - Her first time in Vegas and still leaning to be a slut.
  Tom - Her much older teacher.

- Plot

- Scenes

** On The Road Again
- Story
  V takes a trip with her old-man and gets fucked in a trailer.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Tequila Sunrise
 - Story
   V is fucked while sitting on a wall.

- Characters
  V - On vacation with Tom in Thailand.  she is in full animal sex-mode.
  Tom - Intent on introducing V to all forms of debauchery.

- Plot
  V and Tom take walk at night and talk about their future together.  All of a
  sudden V starts to rub Tom's cock.  He rips off her panties and fucks her
  while she sits on a wall.
 
- Scenes
  
** Trading Places
 - Story
   V agrees to trade partners that witnessed her sucking off Tom.
 
- Characters
  V - Ready to try new slutty things.
  Tom - Traded V to another couple.
  Scott - Husband to Jennifer with an oversized cock.
  Jennifer - Hot and sexy fucks like a pornstar.
 
- Plot
  - After watching V's performance at sunset a married couple proposes trading
    places.
  - V is reluctant at first but then Jennifer pulls our her husbands cock which
    is the biggest V has ever seen.  She immediately agrees.
  - V is alone with Scott and is afraid of his big cock.  He reassures her and
    teaches her how to handle his monster.
  - V learns how to deal with his huge cock by using lots of lube.  In the
    process she comes to love being stretched and pounded deep.
 
- Scenes
  Correspond to the plot.  This is the actual story.

* California Dreamin
** Sidetracked
V sucks dick on the side of the highway on the way to Vegas. V and her lover
have a conversation about sex. Still in the honeymoon phase they are constantly
fucking. V's lover asks where V has sucked dick in the past. V tells him in all
sorts of places theater, parking lot, beach, car. V starts to rub her lovers
cock, he has a hard time concentrating on driving. V's pussy is throbbing, she
is thinking of sucking his cock while he drives. They are on the highway going
to Vegas about 10 miles outside of Barstow in the middle of nowhere.

- TODOS

  - TODO When V starts playing with herself Rick describes her body and why she
    is so sexy. See Delta of Venus "Pierre"

- Characters 
  V - Recently divorced with a new outlook on her sexuality.
  Unburdened by her previous life she pusues erotic adventures all over the
  world. 
  Rick - Met V on a trip to her country and has fallen in love.  What he really
  loves is the way V takes care of him in the bedroom.
  
- Scenes 
  - V's proposes a roadside blowjob. V has a flashback to the year before
    sucking dick in a car. She tells her lover the story but doesn't say who it
    is. It's her previous lover who is also friends with her current lover. She
    thinks about how much better a fuck her former lover is. She asks him to
    pull over and begins to suck his dick.
  
  - V's sucks her lovers cock. She loves a hard cock in her mouth. She's been
    sucking dick since she was 16. She's never had a bad experience sucking
    dick. She loves how it makes her lover feel. She does it out of love.

- Story 
  We were two hours into a four our drive about 10 miles outside of Barstow on our
  way to Vegas.  God, it was hot even though the AC in the truck was going full
  blast.

  Rick is my fiance.  53 years old, somewhat balding, with a paunch for a belly he
  wasn't exactly the stud I imagined but he was a good man and slightly above
  average in bed.  We were introduced a year ago by my former lover, Tom.  Tom was
  20 years older than me and a world renown lover.  That's right I said "world renown."
  Apparently Tom wrote a book on Ancient Lovemaking Techniques and is also a
  lifelong student and teacher of Kung Fu.  I met Tom right around the time I got
  divorced but apparently it was not a chance meeting.  It was actually a setup by
  my very good friends, an attempt to boost my confidence and self-esteem.  To put
  it bluntly Tom was called upon to fuck me back to being beautiful and he was
  quite successful.  He was passionate lover with a sizeable cock who could last as long
  as I needed him too.  I'm sorry I shouldn't be talking about Tom, but sometimes
  I can't help it.  He was truly a good fuck but I will save those stories for
  later.

  Rick wasn't a bad lover but he was no Tom either.  His cock was about two inches
  shorter and half as thick.  I'm not a size queen but after experiencing Tom's
  size it was hard for me to feel anything less. What I did like about Rick's size
  was he was easy to go down on.  Ladies, have you ever tried to suck a thick
  cock? I can tell you that after about five minutes your jaw starts to ache and
  you feel like giving up.

  For the last hour Rick has been asking me about my past sexual adventures.  I
  think this is common with all men, needless to say he hasn't been the first man
  to ask me about such things.  I find it amusing, if you tell them the
  truth they get jealous, hurt, or start lacking confidence. The topic of this
  conversation was oral sex.  The usual stuff how many have you had? Too many to
  count I thought with a smile.  What's the largest you've had? Twice as large and
  thick as you my dear Rick.  Where have you done it? Now that one I was willing
  to answer, just to see his reaction.

  "Where have I gone down. let's see." I said "Locker room, park, movie theater,
  elevator, beach, dorm room, changing room, countless hotel rooms, balconies, boy
  friend's parents house, to name a few."

  The look on Rick's face was priceless, of all the places I named he's probably
  only done it in a hotel room.

  "What's wrong baby?" I said.

  "That's a lot of places to have gone down. Were you ever caught?"

  That's one question I wasn't going to answer. I remembered a time while going
  down on my boyfriend his buddy walked in on us. I was surprised but didn't stop,
  and it's a good thing because my boy friend just started to cum flooding my
  mouth with an ungodly amount of his cum.  Rather than walk out of the room his
  buddy came up behind me and started stroking my pussy, that's another story.  By
  the way there are lots of them.  I found out later that my boyfriend planned the
  "walk-in" with his buddy.

  "No my love I was lucky in that regard."

  Rick said "I noticed you've never done it in a car."

  "You know, you're right.  Would you like to fix that?"

  "I thought you'd never ask." He said.

  Rick pulled over on the side of the highway and pushed his seat all the way back
  to give me room to work.  I unbuckled his jeans and pulled out his cock, it was
  hard as glass and the head was a purplish red.  I could smell his sweat and knew
  he was "pre-cumming" during our conversation.

  I grabbed his cock and stroked it slowly.  I must say Tom taught me well.
  He said the best time to sock a cock was when it was hard.  He said I should
  "tease it til it hurts."  I could tell by the color of his cockhead it "hurt."

  I bent down and slowly ran my tongue around the head. With my other hand I felt
  for his balls and gently massaged them. Ladies, men love it when you play
  attention to their balls, just so you know. Massaging, licking it doesn't matter
  if you are tired and want them to cum right away start playing with their balls.
  I could feel his hardness twictching as I pushed it deeper into my mouth. At the
  base of his cock I applied more pressure with my lips creating the same
  sensation as if he were balls deep inside me. Ladies every man is
  different, you need to find out what gets them off or else you will be making a
  lot of mistakes. Rick likes it slow, deep, and wet.  

  I could tell he was close, Rick could only take about five minutes of sucking
  and then he'd blow his load.

  Sensing he was close I started moving my head faster and added my hands stroking
  and sucking at the same time.

  I could taste his precum oozing more and more and knew he was there.

  With a groan he grabbed my head and held it down.  His cocke started spasming as
  he came deep in my mouth.  I tried to swallow every drop but some of it came out
  the side of my mouth.  I raised my head and continued sucking til he grabbed it
  and held it in place.  At this point I knew it his cock was too sensitive for
  anymore attention.  His cock remained in my mouth but I kept my head still.

  "So, baby how did you like it?" I was teasing him.  I knew he liked it, I've
  never had any complaints in this area.

  "My God baby I love you." He said.

  "I know my love, but keep in mind I will expect you take care of me when we get
  to the hotel."

  I reached inside my shorts and fingered my wetness.  I place my fingers on his
  lips so he could taste it.

  "Yes, my love when we get to Vegas I will be sure to take care of you, or find
  someone who will."

  Now it was my turn to be surprised.  The thought of another cock invading my
  softness was certainly an option.

  I love being a slut.

** Another Vegas Vacation
- Plot
  Rick hires a giggolo to take care of V with the condition that he gets to
  watch.  V is nervous but very turned on, she fucks Jason in the most
  animalistic way.
 
- Characters
  V - Excited to be in Vegas V does things she would never do anywhere else.
  Rick - V's boring fiance shows signs of excitement.
  Jason - Giggolo with a huge cock.

- Story
  Rick follows through with his promise to get her an adequate substitute. 

** Mr. Clean
V discovers an enema kit in her fiances closet.

* Higher Learning
** Lick It Up
- Story
  V's college boyfriend helps her see the light with his active tongue.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Dogs and Cats
- Story
  V wakes up to her pussy being eaten and get a big surprise.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Three's Company
- Story
  V is surprised by a second cock pushing into her from behind.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Professor Proton
V is tutored by her much older professor.
 
* In the Beginning
** First Time
V is taken for the first time inside a locker room.

- Plot

- Characters

- Story

** Watch and Learn
V's friend learns how it's done by watching V.

- Plot

- Characters

- Story

** Sharing
- V's lover takes her friends virginity while V coaches her.
** Hey I Know You
V meets a man who tells her they've met.  V is surprised and does not remember
him.  Apparently they met about three years ago when he was visiting with her
former lover Tom.  Her new friend tells her that she showed no interest in him
and that he remembers seeing her and Tom fuck.  She asks how he saw them and he
tells her that Tom had hidden cameras in the bedroom.  V is mad but turned on
and asks did he like what he saw.  Her new friend smiles and says maybe.
* Movement Tracker
 - 12 Jun 
   Golden took CTO half-day, Silver went to the hospital.  Neither one was back
   when I left at 16:00 
