#+TITLE: The Story of V
#+STARTUP: indent

* How to write Flash Porn
+ [[https://gretachristina.typepad.com/greta_christinas_weblog/2007/10/how-i-write-por.html][Greta Christina]]
  How does it feel to be this person, or these people, having sex? How do these
  sex acts feel physically -- soft, tight, sharp, gentle, smooth, cold? 
  How do they feel emotionally – nervous, urgent, giddy, relieved, beloved, dirty?

  It has to convey what the sex means.  Why the people are having it. Whether
  it's giving them what they'd hoped for. What about it is surprising. Whether
  anything is going to be different now because of this sex.
+ [[http://terribleminds.com/ramble/2012/06/26/25-things-you-should-know-about-writing-sex/][Chuck Wendig]]
+ [[http://www.thereviewreview.net/publishing-tips/flash-fiction-whats-it-all-about][Flash Fiction What it's All About]]   
+ [[https://www.fanfiction.net/s/9661958/1/The-Ultimate-Guide-to-Writing-Smut-Fic][Smut Fiction]]
- [[https://thewritepractice.com/dialogue-tags/][How to use Dialog tags]]
* Who is V?
- Who is V?
- What is her purpose in writing these stories?
  - Lessons learned to help other women.
  - Create a record of her sexual adventures.
- What makes her so sexual?
- She is no different than other women.
- She loves sex and is not afraid to admit it.
  
* Casual Encounters
** Agent 12
- In this story V has an encounter with an oversized cock.

* Old Men
** Sidetracked
*** Characters
V - her usual horny self.
Rick - Her current love interest.

*** Plot
1. V and her lover have a conversation about sex.
   - V and her lover are still in the honeymoon phase which means lots of fucking.
   - V's lover asks where V has sucked dick in the past.
   - V tells him in all sorts of places theater, parking lot, beach, car.
   - V starts to rub her lovers cock, he has a hard time concentrating on
     driving.
   - V's pussy is throbbing, she is thinking of sucking his cock while he drives.
   - They are on the highway going to Vegas about 10 miles outside of Barstow in
     the middle of nowhere.
2. V's proposes a roadside blowjob.
   - V has a flashback to the year before sucking dick in a car.
   - She tells her lover the story but doesn't say who it is.
   - It's her previous lover who is also friends with her current lover.
   - She thinks about how much better a fuck her former lover is.
   - She asks him to pull over and begins to suck his dick.
3. V's sucks her lovers cock.
   - She loves a hard cock in her mouth.
   - She's been sucking dick since she was 16.
   - She's never had a bad experience sucking dick.
   - She loves how it makes her lover feel.
   - She does it out of love.
*** Story
- Scene 1
  I could tell his cock was hard even through his jeans.

  We'd been talking about sex for the last hour or so, him asking me questions
  and me trying to avoid the answers.  Why do men always want to know what
  you've done with other men?   
  
  "Baby would you like to know all the places I've sucked dick?" I asked.
  
  I didn't wait for him to answer.

  "I've gone down in cars, bathrooms, locker rooms, in a park once, theaters, at
  the beach, well you get the idea." I smiled.

  He looked surprised.

  "Wow, you are advanced" He said.  I wondered if I turned him off.

  "Do you disapprove?" I asked.

  "No, not really.  I never expected you to have so many different experiences."

  "Well, I hope it doesn't bother you, after all you've experienced firsthand what
  I've learned from sucking so much cock." 

  "Yes, baby I have."

  I could feel the wetness seeping through my panties.  My pussy was throbbing and
  swollen. I leaned back against the door of his truck and spread my legs and
  started rubbing my pussy.

  "I'm so turned on right now thinking about all the cocks I've had in my mouth.
  Do you mind if I play with myself?"  I reached into my shorts and felt my wet
  panties. I stroked my clit, eyes half closed. "Fuck baby I really need your
  cock in me, why don't you pull over and let me show you what quality cock
  sucking feels like?" 
- Scene 2
  V thought to herself "I've been here before haven't I."

  One year ago I was on the same trip with a different man.  The conversation
  started the same way and ended with his cock in my mouth.

  Jim was a much better fuck than Rick, hell he'd written a book about the subject
  so he better be good.  He was much more livelier even though he was in his 60's,
  yep that's right a 20 year difference.  It was Jim who really taught me to suck
  dick.  Well, let me clarify I've always been good, but Jim helped me think about
  why I was good. 

  Ladies, never suck a soft dick, take your time and get it hard.  

  In this situation Rick's cock was already hard as glass.

  I thought to myself I better make this quick, we don't want to get caught.  In
  my experience the quickest way to make a man cum fast, aside from sticking a
  finger in his ass, is to suck him like a cock starved whore.  So what does that
  mean? Suck him fast, wet, and with lots of head movement.

  I started by trying to choke myself on his cock while producing good amount of
  slobber. There's a way  to take a cock in your mouth that makes it feel like a
  pussy.  The trick is to create a feeling of lightness while maintaining enough
  contact to feel like the walls of your pussy.

  I could tell he was close, his cock was leaking a ton of precum but he hadn't
  yet pulled the trigger.

  All men have there "tells" so pay attention ladies, this is the art of fucking
  that is most ignored.  Reading your partner.  The better the read the better the
  experience.  You need to know his triggers.  What does he do or say right before
  he comes? How about leading up to his orgasm?

  In Rick's case he would put his hands on the back of my head at the same time
  thrusting his cock as if he was fucking my ass or pussy.  Jim liked it when I
  fingered his ass, oh it's not so bad just make sure you use lube, spit is not 
  lube at least not for someones ass.

  "Baby, do you know why I'm so good at sucking your dick?"

  I didn't wait for him to answer.

  "Because I'm doing it with love." I took his whole cock in my mouth and held it.
  I swirled my tongue around the shaft and head.

  He exploded in my mouth.  My God this has always been a turn of for me.  The
  moment a man cums in my mouth. 

** The Great Escape
- V finds time to fuck her lover while visitors are in the house.
- How did he initiate fucking?
*** Plot (four scenes ~ 375 words per scene)
- V's boyfriends friends are vising for the week.
  - She pictures herself fucking one of the friends.
  - She wonders who has the bigger dick.
- V hasn't fucked her boyfriend in two days.
  - She touches herself in the bathroom.
  - She tells her boyfriend how much she wants to fuck him.
  - She offers her boyfriend a threesome.
- V doesn't care who's in the house she is going to fuck her boyfriend.
  - V decides to fuck her boyfriend.
  - V makes out with her boyfriend while one of his friends watches.
  - V's boyfriend fingers her while his friend watches.
  - V's boyfriend fingers her in the kitchen.
- V fucks the shit out of him.  Probably the wildest fuck yet.
  - V's boyfriend eats her pussy from behind.
  - V gives her boyfriend a prostrate massage while milking his cock.
  - The house guests hear whats going on.
*** Story
Story is just that, the story itself.

*** Characters
V - her usual horny self.
Jim - V's lover, professional sex instructor, and 20 years older.
Rick - Jim's friend and potential fuck-interest for V.
Matt - Another visitor.

** I Spy
- V is in Thailand with her much older lover. - She doesn't know it but her
  lover has arranged for a spy to watch their every move in the bedroom.
- V teaches a class on ancient lovemaking.

** The Big Apple
- V says goodby to her old man in style

** What Happens in Vegas Stays in Vegas
- V fucks multiple lovers in Vegas.
- V is horny after sucking dick on the road (Sidetracked) now it's her turn to
  cum.

** On The Road Again
- V takes a trip with her old-man and gets fucked in a trailer.

** Heat of The Night
- V sneaks off to get fucked from behind.

- I couldn't help myself ever since the first time we fucked I couldn't get him 
out of my mind.  Ok, so I'm recently divorced at this point any cock would do,
but with him it was more.  

- "Hey baby" I called out as I entered the room. My God I'm dripping wet and he
  hasn't even touched me yet.  "V what are you doing here this is a nice
  surprise?" 
  
  I smiled knowing that if I said what was really on my mind his cock would be 
  in me in a flash.  "My mom is watching the kids so I thought I'd spend the
  night, is that ok?"
 
- I'd met Jim just two days ago, a gift from some friends if you really must
  know.  Although my divorce was a long time coming it hit me pretty hard.  You
  know the deal low self-esteem, am I beautiful, the usual bullshit that comes
  with a break up.  Jim was the stud who was called upon to make things better.
  He was brought here for one reason, to fuck me back to a state of high
  self-esteem. So far he has lived up to his reputation as a "famous lover"
  hell, he even wrote a book about ancient lovemaking.  How could he NOT be a
  good fuck?

- Tonight would be our first night together.  Finally we could take our time, he
  promised hours of fucking and my anticipation was so high that my pantys were
  soaking wet.  I love sex and love a good hard cock in my pussy or mouth, Jim
  was just the right prescription for my desires. Oddly enough I didn't cum
  first time he fucked me, maybe it was nerves or maybe pressure to perform.  He
  was so understanding.  The second time was mind blowing, everything I expected
  from a good fuck.  He ate my pussy, I sucked his dick, nothing fancy just an
  hours worth of pussy pounding. In the end I came on all fours.

- I lied to him, mom wasn't watching the kids, when I left they were sleeping.
  Don't worry I'm a good mom, my 16 yearold daughter was more than capable of
  handling things and my parents live just two floors up.  I felt dirty sneaking
  away but I guess that's part of the turn on.  Look, I need a hard cock and one
  as good as his is hard to pass up.

- "Sit on the edge of the bed" he said.  I sat down and he walked over unzipping
  his jeans.  Wait, no foreplay I thought.  He pulled out his semi-erect cock
  and grabbed the back of my head.  Sure I knew what he wanted I'd had hard
  cocks in my mouth since I was a teenager. I've never seen a cockhead as purple
  as his and hard as glass.  I never noticed how big it was, it was at least
  eight inches long and thick as a coke can and uncircumcised.  I started
  licking the head but he wanted more and right away.  He grabbed the back of my
  head and thrust his cock as far into my mouth as he could. 

* Higher Learning
** Lick It Up
- V's college boyfriend helps her see the light with his active tongue.

** Dogs and Cats
- V wakes up to her pussy being eaten and get a big surprise.

** Three's Company
- V is surprised by a second cock pushing into her from behind.

