#+TITLE: The Story of V
#+STARTUP: indent

* How to write Flash Porn
+ [[https://gretachristina.typepad.com/greta_christinas_weblog/2007/10/how-i-write-por.html][Greta Christina]]
  How does it feel to be this person, or these people, having sex? How do these
  sex acts feel physically -- soft, tight, sharp, gentle, smooth, cold? 
  How do they feel emotionally – nervous, urgent, giddy, relieved, beloved, dirty?

  It has to convey what the sex means.  Why the people are having it. Whether
  it's giving them what they'd hoped for. What about it is surprising. Whether
  anything is going to be different now because of this sex.
+ [[http://terribleminds.com/ramble/2012/06/26/25-things-you-should-know-about-writing-sex/][Chuck Wendig]]
+ [[http://www.thereviewreview.net/publishing-tips/flash-fiction-whats-it-all-about][Flash Fiction What it's All About]]   
+ [[https://www.fanfiction.net/s/9661958/1/The-Ultimate-Guide-to-Writing-Smut-Fic][Smut Fiction]]
+ [[https://thewritepractice.com/dialogue-tags/][How to use Dialog tags]]
* Template
 - Story
  One-liner on what the story is about.
 
- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes
  Correspond to the plot.  This is the actual story.

* Who is V?
- Who is V?
- What is her purpose in writing these stories?
  - Lessons learned to help other women.
  - Create a record of her sexual adventures.
- What makes her so sexual?
- She is no different than other women.
- She loves sex and is not afraid to admit it.
  
* Casual Encounters
** Agent 12
- Story
  V has an encounter with an oversized cock.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

* Old Men
** Sidetracked
- TODOS

  - TODO When V starts playing with herself Rick describes her body and why she is so sexy.
   See Delta of Venus "Pierre"

- Story
  V sucks dick on the side of the highway on the way to Vegas.

- Characters
  V - her usual horny self.
  Rick - Her current love interest.
  
- Plot
  - V and her lover have a conversation about sex.
    V and her lover are still in the honeymoon phase which means lots of fucking.
    V's lover asks where V has sucked dick in the past.
    V tells him in all sorts of places theater, parking lot, beach, car.
    V starts to rub her lovers cock, he has a hard time concentrating on
    driving.
    V's pussy is throbbing, she is thinking of sucking his cock while he drives.
    They are on the highway going to Vegas about 10 miles outside of Barstow in
    the middle of nowhere.
  
  - V's proposes a roadside blowjob.
    V has a flashback to the year before sucking dick in a car.
    She tells her lover the story but doesn't say who it is.
    It's her previous lover who is also friends with her current lover.
    She thinks about how much better a fuck her former lover is.
    She asks him to pull over and begins to suck his dick.
  
  - V's sucks her lovers cock.
    She loves a hard cock in her mouth.
    She's been sucking dick since she was 16.
    She's never had a bad experience sucking dick.
    She loves how it makes her lover feel.
    She does it out of love.

- Scenes
  - Scene 1 The conversation
    Why do men always want to know about my previous sex-life? Isn't it enough
    that I'm fucking them.  Why do they insist on knowing things that don't matter?
    
    Rick is my fiance, somewhat of a conservative his performance in the bedroom
    is a bit lacking. I don't now if it's because of his evangelical christian
    beliefs or lack of experience.

    He's not a bad lover, he's just not exciting. You know what I'm talking
    about, he goes through the motions, makes me cum, but afterwards it's time
    to move on not worth looking back. If I were to rank my lovers he'd be
    somewhere in the middle.
 
    "So, how many dicks have you had in that talented mouth of yours?" He asked.

    I don't know but I think every woman gets asked this question at least once
    in her lifetime.  If the number is low you tend to answer right away.  If
    your number is high like me, you don't say a word or you lie.  I chose silence.

    "Look, how many dicks, that's off the table" I smiled "But if you want to know
    where that's Ok."

    "Lets see locker room, theater, beach, car, parks, university classroom,
    dorm room, changing room, parents house, to name a few."

    Looking at his face I couldn't help but smile.  The look he had was
    somewhere between shock and awe.

    "Baby, what's wrong you don't look well?" I said.

    "Yeah just a little bit but it's Ok, I suppose all that practice is why your
    so good at sucking my cock, or any cock for that matter."

    I've never had a complaint in that department that's for sure.  When I suck
    cock my goal is to ruin it for every woman who comes after me.  I want those
    men to think of me when they are in the wives mouth.  I want them to see my
    head bobbing up and down, getting their cocks nice and wet.  If you're going
    to do something you might as well do it right.

    I have to admit the conversation had an affect on me. I love sucking Rick's
    dick, it's not huge which means it's fairly easy to suck. My previous lovers
    cock was above average and always caused my jaw to ache after 30 minutes of
    sucking. At the moment my pussy was wet and I wanted to do something about
    it.

    We were about 10 miles outside of Barstow on our way to Vegas.   

    I leaned back against the door of the truck and opened my legs.  I reached
    underneath my shorts and felt my wet panties.  I rubbed my clit and closed
    my eyes.  I could feel my pussy responding with a little contraction.  

    "Oh baby, my pussy is so hot for you right now."

    "Would you mind if I sucked you dry?"
  
  - Scene 2 V sucks Rick's cock
    I opened my eyes to catch his reaction.  Somehow he managed to free his cock
    and was stroking it while driving.  He was hard as a rock and the head of
    his cock was a reddish-purple color.  I knew he was close.

    "Pull over."

    He pulled over on the highway and let the truck idle.  He adjusted his seat
    and leaned back giving me some room to work.

    I took the head of his cock between my lips.  I could taste his pre-cum.

    "Fuck baby, you're an exceptional cocksucker." He said.

    I took the length of his cock in my mouth and held it there.  I swirled my
    tongue around the shaft and head and could feel him begin to thrust his
    hips.  I slowly raised my head while keeping pressure on the shaft.  I was a
    slow luxurious blowjob but I knew he would cum in no time.

    "Oh baby, you taste so good.  I want you to explode in my mouth, but first
    you gotta promise me something." 

    "Yeah sure, whatever you want." He said.

    "When we get to the hotel I want you to fuck me for an hour straight."

    I knew he couldn't last more than 10 minutes of straight fucking, I was
    playing with him.

    "Yes baby I would be glad to fuck you for as long as you like."

    I smiled and continued sucking his cock.  I cupped his balls in my hand
    while my head moved faster.  He places his hand on my head and pushed my
    head down.  Some women don't like this but I think it's a turn on.

    More pre-cum and he started to explode.  I sucked his cock dry swallowing
    every drop.  Normally it only takes about five minutes to make him cum this
    way.  Today it was around three.
  
  - Scene 2
    V thought to herself "I've been here before haven't I."

    One year ago I was on the same trip with a different man.  The conversation
    started the same way and ended with his cock in my mouth.

    Jim was a much better fuck than Rick, hell he'd written a book about the subject
    so he better be good.  He was much more livelier even though he was in his 60's,
    yep that's right a 20 year difference.  It was Jim who really taught me to suck
    dick.  Well, let me clarify I've always been good, but Jim helped me think about
    why I was good. 

    Ladies, never suck a soft dick, take your time and get it hard.  

    In this situation Rick's cock was already hard as glass.

    I thought to myself I better make this quick, we don't want to get caught.  In
    my experience the quickest way to make a man cum fast, aside from sticking a
    finger in his ass, is to suck him like a cock starved whore.  So what does that
    mean? Suck him fast, wet, and with lots of head movement.

    I started by trying to choke myself on his cock while producing good amount of
    slobber. There's a way  to take a cock in your mouth that makes it feel like a
    pussy.  The trick is to create a feeling of lightness while maintaining enough
    contact to feel like the walls of your pussy.

    I could tell he was close, his cock was leaking a ton of precum but he hadn't
    yet pulled the trigger.

    All men have there "tells" so pay attention ladies, this is the art of fucking
    that is most ignored.  Reading your partner.  The better the read the better the
    experience.  You need to know his triggers.  What does he do or say right before
    he comes? How about leading up to his orgasm?

    In Rick's case he would put his hands on the back of my head at the same time
    thrusting his cock as if he was fucking my ass or pussy.  Jim liked it when I
    fingered his ass, oh it's not so bad just make sure you use lube, spit is not 
    lube at least not for someones ass.

    "Baby, do you know why I'm so good at sucking your dick?"

    I didn't wait for him to answer.

    "Because I'm doing it with love." I took his whole cock in my mouth and held it.
    I swirled my tongue around the shaft and head.

    He exploded in my mouth.  My God this has always been a turn of for me.  The
    moment a man cums in my mouth. 

** Heat of The Night
- Story
  V sneaks off to get fucked from behind.

- Characters
  V - Is recently divorced and feeling low in confidence and self-esteem.  She
  needs a man to show her how desirable she is.  She is willing to do or try
  anything to prove herself.

  Jim - Is 20 years older than V and is a trained Kunf-fu master.  He also
  teaches Taoist lovemaking and has written a book about it.  He is a master
  lover and world-famous.  He's been brought in to make V feel like a woman.

- Plot
  - V has a strong desire to be with Jim so she sneaks off at night leaving her
    kids with her mom.
  - V really has a need for Jim's cock.  She wasn't able to cum their first time
    together because she was too nervous.

- Scenes
  - Scene 1: V is at home lying in bed but she can't sleep.  She is torn with anxiety and
    desire because she wants to sneak off and be with Jim.  She has unfinished
    business with him, she needs to cum.
    
  - Scene 2: It's late at night and Jim here's a knock at the door.  He's
    pleasantly surprised to find V standing there in a long coat.  Little does
    he know that underneath is just panties and no bra.

  - Scene 3: V tells Jim that he is the best and that she needs his hard cock.
    She promises to do whatever he wants as long as he makes her cum.  Jim
    smiles and asks her if that's really the deal she wants to make.  She
    answers yes.

  - Scene 4: Jim fucks V and gives her the best orgasm of her life.
** The Great Escape
- Story
  V finds time to fuck her lover while visitors are in the house.

- Characters
  V - her usual horny self.
  Jim - V's lover, professional sex instructor, and 20 years older.
  Rick - Jim's friend and potential fuck-interest for V.
  Matt - Another visitor.

- Plot (four scenes ~ 375 words per scene)
  - V's boyfriends friends are vising for the week.
    - She pictures herself fucking one of the friends.
    - She wonders who has the bigger dick.
  - V hasn't fucked her boyfriend in two days.
    - She touches herself in the bathroom.
    - She tells her boyfriend how much she wants to fuck him.
    - She offers her boyfriend a threesome.
  - V doesn't care who's in the house she is going to fuck her boyfriend.
    - V decides to fuck her boyfriend.
    - V makes out with her boyfriend while one of his friends watches.
    - V's boyfriend fingers her while his friend watches.
    - V's boyfriend fingers her in the kitchen.
  - V fucks the shit out of him.  Probably the wildest fuck yet.
    - V's boyfriend eats her pussy from behind.
    - V gives her boyfriend a prostrate massage while milking his cock.
    - The house guests hear whats going on.

- Scenes

** I Spy
- Story
  V is in Thailand with her much older lover. - She doesn't know it but her
  lover has arranged for a spy to watch their every move in the bedroom.

- Characters
  V - Recently divorced V is discovering her true sexuality and loving it.  She
  has learned things that she could never have learned with her ex-husband.
 
  Jim - 20 years older than V, Jim is showing her the best way to be a slut.

  Ron - One of the hidden friends.

  Matt - One of the hidden friends.

- Plot
  - Jim has been training all day and finally finds time for V.  Jim has
    promised her some special "desserts" on this trip and he plans to deliver.
    He knows the best thing is to let V's anticipation build.

  - V is in a very high state of sexual awareness.  It's her first time in Thailand and
    her senses are overloaded.  V is learning how to be more assertive and enjoy
    her sexual experiences.
 
- Scenes
  - Scene 1: V and Jim have a conversation about sexual acts that may not be
    considered normal.

  - Scene 2: During the conversation Jim takes out his cock and starts to rub
    it.  V immediately drops to her knees but Jim stops her.  He wants to teach
    her to be patient and build anticipation.  He finally lets her suck his
    dick.

  - Scene 3: In the meantime unknown to V two of Jim's friends are hiding in the
    closet.  This is one of the "desserts" he has promised her.  In previous
    conversations Jim told his friends how raw V is and that with a little
    "molding" he could turn her into a world-class slut.  The agree to help.

  - Scene 4: V and Jim start to fuck.  About 30 minutes into the session Jim's
    friend make themselves known based on a pre-arranged signal.  V is surprised
    and a little scared but watching the two men stroke their big cocks has made
    her forget her fear.  Jim promises that all they will do is watch.
** The Big Apple
- Story
  V says goodby to her old man in style

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** What Happens in Vegas Stays in Vegas
- Story
  V fucks multiple lovers in Vegas.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** On The Road Again
- Story
  V takes a trip with her old-man and gets fucked in a trailer.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

* Higher Learning
** Lick It Up
- Story  
  V's college boyfriend helps her see the light with his active tongue.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Dogs and Cats
- Story
  V wakes up to her pussy being eaten and get a big surprise.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

** Three's Company
- Story
  V is surprised by a second cock pushing into her from behind.

- Characters
  Characters, Places, Scenes, Quotations are notes on those things that are to be
  included in the story.

- Plot
  Plot contains the shape of the story, as it is at the time. This gets rewritten
  as I go on. It also acts as a reminder of what I've done so far.

- Scenes

