#+TITLE: Tori's Ancient Art of Lovemaking
#+STARTUP: indent

* Tori's Ancient Art of Lovemaking
*** Exceptional Love
Well, baby I really loved our conversation from last night. I tried to sleep but
my pussy was so hot and wet, so I rubbed my swollen clit thinking about the last
time we fucked. I came so hard thinking of your big cock tearing
into my pussy. My god baby, no one has ever fucked me like that.

*** It's Your Brain Stupid
So, let's get back to our conversation from last night. If you really want to
know what turns me on let me tell you. It's not what's between your legs
although your big cock is a dream, for me, it's your brain. What really
turns me on about you is that you've written a book. Wow, my pussy is getting
wet just thinking about it. A man smart enough to write a book came inside me,
now that's a turn on.  It's your brain, my love, is it ok to call you my
love?

*** Cats and Dogs
I have a theory about touch that I find interesting. Men are like dogs, no
offense, and women like cats, yes pussy cats. Cats are nice and soft, I suppose
that's why men refer to my vagina as a pussy. Yes, baby other men have been in
my pussy, does that bother you? I hope not because I'm sure you've fucked way
more women.

Have you ever noticed how they use their tongues? Dogs are sloppy "lappers," but
cats are "delicate." They both use their tongues in different ways, just like
men and women. Even the texture is different. Dog tongues are rough, and cat
tongues are smooth as silk. As you can imagine men eat pussy differently than
women. I love it when a man eats my pussy I can assure you that women are just
as good wink, wink.

*** Little Touches
Baby, I think you know by now that I absolutely love "little touches." I'm not I
love the way you rub my back and how you slowly move up to my neck. Did you know
that the part of the next just under the hair is very sensual? Of course, you
do. I love how you kiss me tenderly while caressing my neck. I'm getting
goosebumps just thinking about it.

I believe this is how you prepare your partner for the pleasures to come. You
create a sexual tension that ends with a massive explosion. As you know, I can
be very impatient when it comes to orgasm. Once my pussy is turned on all I want
is your hard cock deep inside of me. I think you should teach me to slow down
and enjoy the buildup.

I am so grateful to you for teaching me all the things I should have learned
when I was younger. Unfortunately, I've never had a man as talented as you when
it comes to spreading my legs and exploring my cunt. I'm convinced you are the
BEST!

*** Slowhands
Baby, I know how gentle you are, but I also know that you can be an aggressive
animal.  On our last night together you fucked me for over two-hours and I loved
every minute of it.  I have to get used to your big cock my pussy was aching for
a week after you left.  Don't worry my love, there I go again, you just need to
fuck me as much as possible that's the only way I will get used to your monster.

The firs time you fucked me I didn't cum thank you for being so understanding
and gentle which  is exactly what I needed at the time.  The second time we
fucked OH MY GOD baby, that was without a doubt the best fuck I've ever had in
my entire life.

To be totally honest I've had many lovers.  What can I say I love to fuck and
suck, and I can tell by the way you fuck me that you love it too.

*** Almost There
After some deep soulful kissing, you may think it's time to eat my pussy. Wrong!
Please, please, do not forget my lovely tits. Take my nipples in your mouth, use
your tongue, gently take them between your teeth the way you know how. After
getting my nipples hard, it's time to massage my tits and really treat them as
if they are the most important part of my body. Use your palms and go round and
round. Pinch my nipples, lightly, and roll them between your fingers. You know
how much this turns me on. My pussy is throbbing and wet, I can't wait to get
your big cock in my tight pussy.

*** Just The Tip
Baby the next time we fuck could you please rub your huge cockhead on my clit.
Yes, my love I have a few tricks of my own. I remember my very first lover
teaching me this trick. He started fucking me when I was 16 but for the first 10
or 15 times I couldn't cum. The one day after sucking his cock, he started
rubbing his cockhead on my clit. Oh my God I came so hard. Ever since then this
trick has always been a guaranteed orgasm for me.

This is the one move I teach all my lovers. I can't wait to see you in
Istanbul I feel like I have so much to learn from you.  Don't get me wrong I
have a lot of experience but what you've shown me is beyond my imagination.  In
the past I'd get on my back or on my knees and get fucked but you've opened up a
whole new world for me.  Can I tell you a secret? I want to become a dirty
little slut.  I know this is what turns men on and I want you to teach me,
pleeeease.

*** Mouthful
Ok, my lion are you ready to eat my pussy? I love it when you lick the hood of
my clit, feel how hard it is, I feel so sexy opening my legs for you. That's
right baby take my clit between your lips and suck on it. I can feel my pussy
juice running into the crack of my ass, I've never been so wet.

I'm losing control, my love, can you feel how my body is moving. I love grinding
my pussy against your hard tongue. How do I taste? Baby can you please suck on
my pussy lips?, thank you so much, my love, it feels soooooo heavenly. Now
thrust your tongue deep into my cunt, that's it baby lick that pussy.

Wow, I didn't know my legs could spread so far apart, you make me feel like a
dirty slut. That's it, baby, finger my pussy, reach in deep and rub that special
spot you showed me during your last visit. See how my pussy lips are swollen?
I want your cock in me right now, that's it baby pound me as hard as you can.
Your huge cock is such a turn on, fuck baby your cock is white with my juices.
Don't stop baby please don't stop, that's it deeper my love.  I love you James,
I'm cumming baby, I fucking love yooooouuuu.

*** My Lion
Baby, have you ever met a lion? That's you my love, my hard-fucking-big-cock
king of the jungle.  How did you become a "V" expert so quickly? I told my
friend about you, yes Konstantin's wife.  I told her what an awesome fuck you
are, no I didn't say "fuck" but she could tell by the look on my face that's
what I meant.

You know exactly what I want as if you were reading my mind. In the past I've
always thought uncircumsised cocks were scary but yours is perfect.  I love
licking the head of your cock even though it's "covered".  It takes a real woman
to know what it takes to get it to cum out and play.  Baby be honest, am I a
real woman?  God I want to tell the whole world how good you fuck me.  I guess
for now we will keep it our secret, just please don't ever stop fucking me.

*** Three is Not Company
I'm am 100% your lioness if you will have me. I am looking forward to meeting in
Istanbul you said you have a surprise for me. I'm yours, my love, whatever you
want me to do. I know we talked about group sex and I've thought about it. I
trust you and if you want me to experiment with such things I will. In fact, I'm
about to play with my tight pussy and fantasize about that threesome you talked
about. I would love my first one to be with you.

I imagine myself and another woman with you but if you prefer a man that's fine.
I think it's a bit scary, but the thought of two men treating me like a dirty
whore gets me so wet.

I can't wait baby I think I'm going to lay back and take
care of myself, writing this letter has taken me to the edge.  Don't worry it's
your big beautiful cock that I'm craving for, I want it in my mouth and pussy so
bad.

I love you (is it too soon) talk to you tomorrow.

"V"
*** Beginnings
- V's first time on her kneew
- V has another encounter
- V invites her friend to the party and watches as she gets pounded
