#+TITLE: Corp Operations Rules v0.0
#+AUTHOR: Vincent 'TJ' Taijeron
#+STARTUP: indent

* Set Up
* Sequence or Play
1. Air Deployment
   1. Both sides assign Air Units to the Northern or Southern Sectors.
   2. Assign air mission to aircraft: Command, Tactical, and Air Superiority.

2. Air-to-Air Combat
   1. Command Mission Aircraft Attacks declared and performed (by Sector).
   2. Air to-Air Combat (by Sector).
   3. Surviving aircraft may perform their assigned missions.

3. Opfor Attacks
   1. Add or remove Assets. Assets may not be transferred.
   2. Add Support Markers (maximum 6 per Turn). 
   3. Attempt to place Tactical Mission Air units in any space to perform Ground attacks (by Sector).
   4. Perform Ground and Air Attacks.

4. Opfor Movement
   1. Bluefor attempts to place Tactical Mission Air Units in Spaces to perform
      Interdiction (by Sector). 
   2. May Breakdown 4 AR Infantry or 5 AR Armor Movement of Ground Units,
      including attempted placement of up to 3 off-board Airborne Units. 

5. Bluefor Movement
   1. Opfor attempts to place any Tactical Mission Air Units in Spaces to
      perform Interdiction (by Sector). 
   2. May Breakdown 4 AR Infantry or 5 AR Armor.
   3. Movement of Ground Units, including attempted placement of up to 3 off-board
      Airborne Units.

6. Bluefor Attacks
   1. Add or remove Assets Add Support Markers (maximum 6 per Turn). 
   2. Attempt to place Tactical Mission Air units in any space to perform
      Ground attacks (by Sector). 
   3. Perform Ground and Air Attacks.

7. Reinforcements
   1. Each side receives 1 Support Marker. 
   2. Both randomly draw 3 Air Units if available. 
   3. Each side may receive 3 Ground Unit replacements Bluefor draws and places 3
      Reinforcements and offboard Airborne Units may arrive as Reinforcements. 
   4. Opfor draws and places 1d10 on Turns 1 and 2, or 1d10 halved
      (round-down) thereafter, and offboard Airborne Units may arrive as
      Reinforcements. 

* Attacking
** Assets
Assets are additional units that are added to a unit that provide additional
capabilities or bonuses.

  1. A player may assign assets to a unit at the start of their Attack step.
  2. A player may remove an asset from a unit at the start of their Attack
     step.
  3. A player CANNOT reassign an asset from one unit to another.
  4. Bluefor assets must be assigned to units with matching nationalities.
  5. Opfor assets must be assigned to the correct army.
  6. Opfor striped assets may be assigned to any army.
  7. A maximum of 2 assets may be assigned to undamaged units.
  8. If a unit has 1 or 2 hits only 1 asset may be assigned.
  9. If a unit is assigned 2 assets and takes a hit the player can decide
     which asset to return to the asset pool.

 Asset Types
  * Artillery Asset – Increase Attack Rating of Unit by 1 
  * Armor Asset (Opfor only) – Increases AR of Unit by 1 
  * Engineer Asset – Unit ignores rivers, both when attacking and moving.
  - Detection assets.
  - Information assets.
  - EW assets.
  - C2 assets.

** Support Markers
- Place Support Markers before any Attacks are made. 
- The Opfor can play up to 6 Support Markers per turn.
- Bluefor can play up to 2 per Turn. 
- Allow the front Unit to roll 2d10 and pick the best result. 

Can place 2 Support Markers on a space with an Armor Unit to the rear,
allowing any Breakthrough attack to also roll 2d10 and pick the best result,
but if the first space is not cleared the extra Supply Marker is discarded
unused.

All Support Markers are discarded after used.

** Place Air Units attempting Ground Attacks
- Place all Air Units from Tactical Missions by Sector with up to 3 per
  space wish to perform ground attacks against. 
- The opponent then rolls on the appropriate Airstrike loss table for each
  (see tactical Air Missions).  
- Airstrikes that survive can then be used to Attack Ground Units in their space at any
  time during the Attack Step.

** Land Unit Attacks
- Land Units can attack enemy Land Units in an adjacent space. 
- Each Unit may only attack one enemy space per Turn. 
- If 2 Units in the Attackers space only the front unit attacks. 
- If 2 Units in the opponents space only their front unit is attacked
  initially but if retreats or eliminated get to immediately attack the
  second Unit. 

Roll 1d10 against the Units modified AR 
| Asset                                               | Modifier |
|-----------------------------------------------------+----------|
| AR per Artillery Asset                              |       +1 |
| AR per Armor Asset                                  |       +1 |
| if across a minor river (negated if Engineer Asset) |       -1 |
| if across a major river (negated if Engineer Asset) |       -2 |
| if into a Forest space                              |       -1 |
| if into a Rough space                               |       -1 |
| if Armor Unit attacking into a city space           |       -1 |


If Roll equal or less the modified AR (or 1) the attack succeeds.
  * Roll equal to modified AR - the opponent can take a Hit or retreat. 
  * Roll below AR but greater than 1 – opponent takes a Hit and retreats. 
  * Roll of 1 – if modified AR equal or higher than opponents modified (for
    Assets) AR the Unit is eliminated and loses an Asset (chosen by the
    controlling player), otherwise if  AR below opponents AR the Unit takes
    a Hit, retreats and loses an Asset. 

** Hits
Hits are marked on the Unit using a damage flag 
 * 1 to 2 AR Unit is eliminated on first Hit 
 * 3 AR Unit can take 1 Hit 
 * 4 or 5 AR Unit can take 2 Hits.

** Retreats 
- Can retreat into any adjacent space holding 1 friendly Land Unit (cannot
  retreat into space holding 2 friendly Land Units) 
- Can retreat into an adjacent empty space providing are no closer to enemy’s
  map edge in spaces than space retreating from.
- Additionally must retreat into a space that is not adjacent to an enemy Unit
  if possible. 

** Breakthrough
- If a space attacked is cleared of enemy Units, have an Armor Unit in the same
  space and at the back of the attacking Unit, can use this to perform a
  Breakthrough. 
- Cannot perform a Breakthrough over a major river (unless the Armor Unit has
  an Engineer Asset) The Armor Unit is moved into the cleared space and can
  then attack enemy Units in an adjacent space (even against previously
  retreated). 

* Movement
- Opponent places Air Units Attempting Air Interdiction The opponent
  places any Air Units in Tactical Missions by Sector with up to 2 per space wish
  to perform Air Interdiction. 
- Once all are placed, the opponent then rolls on the appropriate Airstrike loss
  table for each (see tactical Air Missions).
- Any remaining will then get to perform Air Interdiction against each Land Unit
  that enters that space.

** Division Breakdowns
Each player has 12 Breakdown Units, broken down into 4 groups numbered 1, 2, 3
and 4. 

Each group represents the components of a Division with Bluefor further dividing
into 2 US groups and 2 WG groups.
  * 4 AR infantry replaced by 2, 1, 1 group. 
  * 5 AR Armor replaced by 2, 2, 1 group. 

Bluefor Units must be broken down into a group of the same nationality. 

If the Unit has a Hit replace with any 2 Breakdown Units of that group, whilst if 2
Hits replace with any 1 of that group. 

Cannot recombine breakdown Units back into a division. If all breakdown Units
of a group are eliminated, another Unit can reuse them. 

All breakdown Units of a group are placed in the same space but must have a
maximum of 2 Land Units per space at the end of movement. 

** Movement of Ground Units
Normally each Land Unit can move up to 2 spaces but not into any space
containing enemy Land Units. If a Land Unit does not start and does not move
adjacent to a space holding an enemy Land Unit can move up to 4 spaces that
Turn. 

If cross a minor or major river then movement is reduced by 1 space,
unless have an Engineer Asset when is ignored. 

Additionally during movement can freely rearrange any spaces holding 2 of
their Land Units front-to-back.

** Moving Through Cities
If a Land Unit enters an enemy controlled City they capture it, place a Control
marker, or flip if a Control maker already there. 

The Land Unit can continue moving.

** Crowding
At the end of a players move cannot have more than 2 Land Units per space. 

If more than 2 Land Units the player must eliminate any excess. 

When a second land Unit enters a space, including retreats, must arrange so
one is placed in front of the other.

* Reinforcements 
** Support Markers
Each player receives 1 Support marker placed in their pool.

** Air Reinforcements
Each player randomly draws 3 Air Unit reinforcements if available.

** Replacements
Land Units with Hits can remove one Hit if not adjacent to an enemy Land Unit
and within 2 spaces of a friendly city that has never been held by the enemy
(cities with a control marker cannot be used for replacements). 

Each player can only repair up to 3 Units and only 1 Hit per Unit.

** Land Reinforcements
Bluefor randomly draws 3 Land Unit reinforcements with Belgium, France and
Netherlands Units starting in their native countries, whilst WG, US or UK
set op on or next to a Bluefor controlled city in West Germany.

The Opfor randomly draws 1d10 on Turns 1 or 2, or 1d10 halved
round-down, on subsequent Turns, Land Units which are place on or next to a
Opfor city not controlled by Bluefor .

Reinforcements cannot be placed adjacent to enemy Land Units and can never
have more than 2 Land Units per space. 

Both players are free to bring on off-board airborne Units, provided not
aborted from an attempted air transport move this Turn.

* The Air/Land Game
** Color coded Attack Ratings
 * Yellow AR – roll 2d10 when attacking other Air Units, against land units
   have 1d10 and 1 AR  
 * Green AR – roll 2d10 against Land Units but against other Air Units have
   1d10 and 1 AR  
 * Black AR – Attack both land and air with 1d10 using same AR for both

** Stealth Fighters 
The 2 Bluefor F-19s have several special properties
  * On first Turn an F-19 on an Air Superiority Mission can choose to Attack the
    Opfors Command Mission Aircraft in that Sector and no Opfor
    Air Units can be used to attack them. If both F-19s in same Sector can
    use both in that Sector. 
  * On Tactical Missions with an F-19 the Opfor has a +2 on Airstrike loss
    roll. 
  * If F-19 used in Air-to-Air combat Opfor Air Units have -2 AR
    against them (minimum of 1). 

* Air Deployment
Place a divider down the middle of the Air Board so neither player can see
the opponent’s side, only revealing when both have placed their Air Units.

Each player secretly divides their Air Units amongst the Northern and
Southern Sectors Missions – Command Tactical or Air Superiority. 

Command Missions are for AWACs only If have 2+ Air Units assigned to a particular
Mission type must assign Air Units to both Sectors and must have at least ¼ of
those Units in the weaker Sector.

** Command Mission and Air-Air Combat 
If 1+ AWACs in a Command Mission then all
air-to-air attacks for that Sector are increased by +1 AR.

** Attacking Command Mission Aircraft
These are assumed to occur simultaneously but with the Opfor declaring
first, may assign up to 1 Air Unit from each Sectors Air Supremacy Mission to
attack the opponents AWACs in that Sector. 

The opponent gets to use as many Air Superiority Mission Air Units in that
Sector as wished to perform air-to-air attacks against the opponents Air Unit
(exception F-19s on first Turn), and only if survive this does the Air Unit
get to perform air-to air attacks against the AWACs.

Regardless of the outcome all Air Units used are removed from the Air
Board.

** Air Superiority
Each Sector is performed separately. Opfor matches up the opponents Air
Superiority Air Units matching up as evenly as possible. 

Must assign 1 Air Unit against an enemy Air Unit before can assign a second, etc. 

If outnumbered can use Air Units with Yellow AR to attack 2 enemy Air Units
with 1d10 against each. 

If equal or outnumber each can only attack 1 Air Unit. Once the Opfor has
performed all their attacks the process is reversed with the Bluefor player
matching up their Air Units to those of the Opfor

** Air-to-Air Combat Effects
All attacks are assumed to occur simultaneously 
  * If roll equal to AR enemy Air Unit is Aborted 
  * If roll under AR enemy Unit is Damaged and Aborted 
A Damaged Air Unit is flipped over if blank or have already been Damaged are
eliminated instead. 

An Air Unit suffering more than 1 hit is eliminated. 

Each Air Unit Aborted, Aborted and Damaged or Eliminated is placed in the
appropriate box, only after all attacks have been rolled by both sides are
these acted upon.

Aborted are removed off board for use in another turn, Aborted and Damaged are
flipped to their Damaged side and also placed off-board, whilst eliminated are
permanently removed from play. 

If both players have 1+ Air Units (or both have 0 Air Units) in a Sector,
then is contested.

If only 1 player has Air Units in that Sector then they have Air Superiority.

** Tactical Air Missions
Any Air Units in a player’s Tactical Mission boxes by Sector on the Air board
can be used to perform attacks or interdict enemy Land Units in the
opponents move. 

*** Airstrike Loss Tables
Regardless of when placed, opponent rolls 1d10 against every Unit attempt to
place on the board. 
   * -1 Helicopter 
   * +1 space contains no enemy Units 
   * +1 space contains friendly Unit (paratroopers dropped this Turn NA) 
   * +2 US F-19 
Consult the Airstrike loss table by Air Superiority in that Sector of the
player placing the Unit.  
   * An Aborted unit is placed off-board. 
   * An Aborted and damaged unit takes damage (or a hit if airborne Unit), if
     survive is placed off-board.  
   * A damage and mission performed takes damage (Hit) but if survives is placed on
     board. 
   * Mission performed means successfully brought down.

*** Terrain Effects on Tactical missions
For both Air Attacks and Interdiction the Air Units AR may be modified, down
to minimum of 1 AR. 
   * Forest -1 AR 
   * City -1 AR

*** Air to Ground Attacks
At the start of the Attack Step can attempt to place up to 3 Air Units per
space holding enemy Units by Sector. Once all placed the opponent rolls for
Airstrike loss against each.

Remaining Air Units can then attack enemy Units in that space at any time
during that Attack Step Can attack any Land Unit, regardless of if front or
behind or can attack one of the Land Units Assets.

  - If roll AR or less the Land Unit takes one Hit or if against Asset is
    eliminated.

If a Green AR then get to perform 2 attacks, either against the same Unit or
Asset or against another, but the targets must be declared before make the
first roll.

Air attacks do not force a Land Unit to retreat and nor does rolling a 1
have any special effect.  

As Air Attacks are performed remove the Air Unit off- board

*** Air Interdiction
At the start of a player’s Movement Step, opponent can attempt to bring down
up to 2 Air Units per space by Sector. Once all placed opponent rolls for
Airstrike Loss against each. 

Remaining Air Units then perform Interdiction against each and every Land
Unit that moves into their space that Turn.

If equal AR the Land Unit stops move. If less than AR, land Unit stops move
and takes 1 Hit. 

If a space being Interdicted by enemy Air Units contains 2 Land Units no
further Land Units can enter that space.

At the end of the opponents move all Interdicting Air Units are removed
off-board.

* Air Transport
During a players movement can attempt to bring down up to 3
Airborne Units by Air Transport. 

Place the Airborne Unit on an appropriate space, the opponent then gets to
roll on the appropriate Airstrike loss table (see Tactical Air Missions).

Aborted Units cannot be brought on by air transport or as reinforcements
until a future Turn.

Moving by air transport, counts as the Units entire move. Once brought onto
the map an Airborne Unit cannot again use air transport.
  * Paratroops – can only be placed on a clear space (not a rugged, forest or city
    space) without enemy Land Units. 
  * Airmobile – can be placed on any space holding a friendly Land Unit,
    including a paratroop Unit also brought on by air transport that Turn.

* Chemical Munitions
Both players have special Chemical Assets, 5 for the Opfor and 2 for
Bluefor.  

   - A Chemical Asset adds +2 AR to that Land Unit

Bluefor cannot use (including placing) their chemical assets until after the Warsaw
Pact has used any of theirs. 

If the Opfor uses a Chemical Asset (defined as placing one on any Land
Unit), immediately remove all remaining EG Units from play.

* Assets
| Asset     | Modifier                  |
|-----------+---------------------------|
| Artillery | +1 AR                     |
| Armor     | +1 AR                     |
| Chemical* | +2 AR                     |
| Engineer  | Rivers NA attack and move |
 *Opfor must use first and lose all EG Land Units

* Terrain Effects
| Terrain     | Ground        | Tactical Air |
|-------------+---------------+--------------|
| Rough       | -1            |              |
| Forest      | -1            |           -1 |
| City        | -1 (Armor)    |           -1 |
| Minor River | -1 (Eng NA)*  |              |
| Major River | -2 (Eng NA)** |              |
+1 Space of movement to cross (Eng NA)
+1 Space of movement to cross no Breakthrough (Eng NA)

* Airstrike Loss Table Modifiers
| Aircraft                 | Modifier |
|--------------------------+----------|
| Helicopter               |       -1 |
| US F-19                  |       +2 |
| Space with no enemy unit |       +1 |
| Space with friendly unit* |       +1 |
 *Unless Paratrooper brought in by air transport that turn.

* Thought and Ideas
** Decisions
The player must decide what a unit needs to do.  He then needs to decide what
weaknesses that unit has that need to be mitigated.  He needs to know how he
will apply that units abilities during the operation.  He needs to decide
when everything is going to take place an in what sequence.

The missions are simple for example deny the enemy this, or destroy the
enemy.  There's no need for a lot of explanation.  The difficulty lies in how
to go about doing those things.  What units to do what tasks? What tasks need
to be done first?  

** Combat
 - Simple Combat system.
 - Potential Combat Power is reflected on paper and based solely on material
   and equipment.
 - Adjusted Combat Power uses factors such as training, experience, and
   leadership to adjust the PCP.
 - Applied Combat Power this is the combat power that can be applied during
   actual combat operations.  ACP is affected by enemy actions.

   I think a simple ratio system will work for units that are battalion or
   higher.  The challenge should be in applying the adjusted combat power to
   an operational target.  

   So how do you apply combat power?
   - Get into a position of advantage like flank or rear.
   - Mass or overwhelm the target by adding units to the operation.  Note this
     can be a double edged sword because too many units will get in each
     others way.  An enabler needs to be added in order to control multiple
     units.  More units mean more or better enablers.
   - Use the right unit for the job.  For example a light infantry unit will
     be useless against an armor unit in open terrain.
   - Use the right enablers.  A light infantry unit could be successful vs an
     armor unit if it had the right enablers.

** What are enablers?
Enablers add additional combat power or special ability.  Organizing
units with special abilities is how you tailor a units abilities and add
additional capabilities.  This is how a light infantry
unit is able to beat or equal an armor unit in the open.

Enablers may have many capabilities but can only use one when assigned to a
unit.  In other words the player must choose what capability is the most
important to that unit and its mission.  For example if an enabling unit
can enhance information gathering or detecting units it can only use one of
those abilities.

Enablers have different ratings which means some units are better than
others at doing the same thin.  This adds another element to the decision
making process.  

Information regarding the enemy is an enabler.  Military Intel units are
the ones who collect and analyze this information.  They are an enabler for
more effective combat operations.

Recon units can detect enemy units faster and more accurately and are more
likely to survive.  The information they collect is used by the intel unit
to further enhance information regarding the enemy.

Electronic Warfare units counter-enemy attempts at gathering information or
disrupts enemy communications.  This is a negative penalty and applies to
adjusted combat power.

Air defense units deny enemy access to certain areas while providing
protection to friendly units.

Engineer units enable mobility, counter-mobility, or survivability.

** Effects
- Slow or stop the enemy.
- Add additional combat power.
- Enable a unit to move faster.
- Enable a unit to ignore obstacles.
- Enable a unit to operate against multiple enemies.
- Enable a unit to conduct operations with units from other organizations.
- Enable a unit to quickly and accurately detect enemy units.
- Enable a unit to sustain itself and stay in the battle longer.
- Enable a unit to recover from exhaustion.

** Task Organization
Tasking organizing units is how a player adds capabilities to another unit.
For example an armor unit is strong against certain types of units depending
on the terrain.  We could add a armored infantry unit which would further
enable the armor unit to operate in certain types of terrain or engage
certain types of enemy. In this case we would use the infantry units ability
to fight other infantry units.

Players must "design" or task organize their units to accomplish their
mission under specific circumstances.  Two considerations would be enemy
capabilities and terrain.  By task organizing a player can counter certain
negative effects or enhance current strengths.  The best example is
overcoming difficult terrain like a river.  By adding an engineer unit with a
bridging capability rivers no longer are obstacles. 

** Stacking Penalty
You may think that adding a bunch of the same enablers will benefit the unit
but that is not the case.  Adding enablers of the same type does not
automatically make a unit stronger.  There are diminishing returns associated
with using the same enabling units.  In other words before you use two of the
same enablers in one unit you may be better off taking that second enabler
and assigning it elsewhere.

Think of it as if you are overloading the HQ.  Hmmm, maybe that's how we
model this.  A HQ has a limited ability to command and control so many units.
The quality of a HQ can be measured in its ability to C2 many units.  In
other words the more units it can C2 the better a HQ it is. Once a HQ is
overloaded it will have a negative effect on the unit.  

- Negative Effects
  - The enabling unit is no longer effective.
  - The unit moves slower.
  - The unit has applied combat power.
  - The unit becomes disorganized.  I think this is the best effect.

** Posture or readiness
It is important that units be able to transition from one posture to another
quickly and efficiently.  This takes planning.  Transitioning from one
posture to another is sequential.  In other words a unit cannot transition
from a static defense to an all out attack. 

Hasty Advance (HA): Units spend movement points normally. May not be given to
units with Deliberate or Prepared Defense orders. Entering this posture costs
half of the unit's movement points if previous posture is other than Hasty or
Administrative Advance.

Deliberate Advance (DA): Units spend twice the normal movement points per hex.
Units in this posture may advance into a hex vacated by retreating or
withdrawing opposing units. May not be given to units with Deliberate or
Prepared Defense orders.

Prepared Advance (PA): May be issued only to units with DA orders that did not
participate in battles during previous turn. Units that conducted offensive
operations while in PA posture must downgrade to DA, HD, or HA the following
turn. No Movement allowed except for advancing into hexes vacating by
destroyed/retreating opposing forces.

Hasty Defense (HD): May be given to units in any Posture.

Deliberate Defense (DD): May be issued to any unit with HD orders. Units with
those orders may not move (except to retreat) or initiate battle. They may not
move into vacated hexes. Units with DD orders that performed offensive
operations must downgrade to HD or HA during the following turn. Entering any
Advance posture from PD costs half of the unit's movement points.

Prepared Defense (PD): May be issued only to units with DD orders. Units with
those orders may not move or initiate battle. They may not move except to
retreat. Entering any Advance posture from PD costs half of the unit's movement
points.

Administrative Advance(AA): Unit may use the road movement rates. It may not
enter hexes adjacent to opposing units or initiate battles. Units in contact
with opposing ground forces may not be enter AA posture. Entering this posture
costs half of the unit's movement points, unless previous posture is Hasty
Advance.
   
One mechanism could be to give a unit it's next order using the "on order"
command.  This would enable a unit to transition from its current posture to
whatever posture was given in the o/o command.  BUT if the player anticipates
incorrectly and issues a different order from the o/o then a severe penalty
is incurred.

Planning
To add another element of planning we offer the player two ways to transition
quickly from one posture to another.  The drawback is a penalty in
performance during the transition.  Of course units with more experience or
better leadership will not lose ability during the transition.
   - On Order - The unit will perform its current task at 80% proficiency, but be
     able to instantly transition to its o/o tasking at 80% proficiency.
   - Be Prepared - The unit is preparing for the next order but will currently
     perform its current task at 100% proficiency.  If it executes its prepared
     task it will do so at 60% proficiency.
