#+TITLE: Resume
#+STARTUP: indent

* Personal Info
Vincent R. Taijeron
22 French Blvd Apt 20, Odessa, Ukraine 65000
(38) 099 529-0612
vincent.taijeron@gmail.com

Passport: 464063378
Expires: 29 SEP 2020
** Clearance

 LGolle@alionscience.com
 PSI Adjudication of NACLC OPM, Opened 2014 05 09, Closed 2014 06 09, determined Eligibility of Secret on 2014 06 13 DOD CAF


* Cover Letters
** Cover Letter 1
Vincent R. Taijeron
22 French Blvd APT 20
Odessa, Ukraine 65000

28 MAY 2014

DynCorp International Free Zone
The Mobile Training Team position is an outstanding opportunity that would allow me to contribute over 30 years of experience in training, education, and mentoring.
As an instructor at the United States Military Academy, I taught tactical decision making, and problem solving in one of the most challenging academic environments in the country.
I have developed programs of instruction for the Defense Strategic Studies major, Behavioral Science and Leadership first and third year leadership classes, and the Department of Military Instruction military science curriculum.  My most recent experience has been teaching and developing courses for the Ground Forces Academy-Odessa.  This has been a very rewarding experience especially in light of the recent conflict with Russia.
I am equally at ease in the classroom or in the field, and I have the experience to prove it.
In addition to my West Point and CGSC academic experience, I also have over 20 years in the military as a senior NCO, and over 20 months of current experience working as an Embedded Police Mentor in Afghanistan.
I think that I am a perfect candidate for the Mobile Training Team position and that my experience and skills would directly contribute to the success of this mission.

Sincerely,

Vincent R. Taijeron

** Cover Letter 2
Hiring Manager,

I am writing in response to a request for confirmation by Shannon Simrell in regards to my interest in the OSCE Monitor position.
For the last 10 months I have been teaching a NATO based curriculum at the Land Forces Academy in Odessa, Ukraine.  Prior to my Ukraine assignment I served as a mentor to the Afghan National Police in Khowst province Afghanistan.  Combine that with my 30 years of experience with the US Army, and I think I make the perfect candidate for this position.
 - I have a great working knowledge of Ukraine, its culture and politics, and I am currently residing in Odessa on a full time basis.
 - In Afghanistan I was an advisor to the senior general who was responsible for the entire Khowst province.  I reported to him on the status of his police units, their capabilities, and evaluated them on humanitarian issues.
 - I participated in over 100 key leader engagements with Afghan elders, political, and military leaders.  My participation included mediating disputes between rival tribes/neighbors, conducting criminal investigations, and security assessments.
The last 10 months here has been a great experience.  In light of the current situation I would like to continue my support of the Ukrainian people.  I think this job would be a great way to contribute.
Thank you for your consideration.

V/r

Vincent R. Taijeron

** Cover Letter 3
I am writing in regards to the Physical Security Specialist position.  The Physical Security Specialist position is an outstanding opportunity that would allow me to contribute over 30 years of experience in security, force protection, and operations.
In addition to operational experience I also have extensive experience writing and implementing SOPs, and force protection policies and procedures.  I have experience as an enlisted senior staff member, and I have operational experience on the ground.  I know how to apply and enforce standards.  In addition to my operational and staff experience I have a very strong IT skillset that enables me to function in today's high tech work environment.
I think that I am a perfect candidate for the Physical Security Specialist position and that my experience and skills would directly contribute to the success of this mission.  Please accept my resume for consideration.
I am writing in regards to the Field Security Officer position. The Field Security Officer position is an outstanding opportunity that would allow me to contribute over 30 years of experience in security, force protection, and operations.
In addition to operational experience I also have extensive experience writing and implementing SOPs, to include force protection policies and procedures.  My combat and operational experience would be invaluable in my day to day operations as a field security office.
My military leadership experience is perfect for this type of position.  I know how to apply and enforce standards, as well as motivate and train individuals and teams.  In addition to my operational and staff experience I have a very strong IT skillset that enables me to function in today's high tech work environment.
I think that I am a perfect candidate for the  Field Security Officer position and that my experience and skills would directly contribute to the success of this mission.  Please accept my resume for consideration.
For the last 10 months I have been teaching a NATO based curriculum at the Land Forces Academy in Odessa, Ukraine. Prior to that I served as a mentor to the Afghan National Police in Khowst province Afghanistan.  Combine that with my 30 years of experience with the US Army, and I think I would make the perfect SME.
I have a very diverse background in training and education as it pertains to military and police leadership.  I have developed exercises at West Point and the Command and General Staff College.  I can apply Outcomes Based Education or Systems Approach to Training to POI development.
In addition to my classroom expertise, I also have extensive experience in the field as a trainer, or observer controller.  For two years I operated with the US Army and the Afghan National Police in Khowst province.  I did not just sit on the FOB, I went on regular patrols in order to mentor, and train the ANP.
My classroom and field experience enables me to apply multiple skillsets to a variety of training and education requirements.

Thank you for your consideration.


* KSA
- Secret Security Clearance (Security review 2014)
- Proven ability to operate in dynamic volatile environments while under pressure
- Over 30 years' experience providing force protection, physical security, and combat operations
- Proven ability to clearly and concisely convey written information orally and/or in writing to individuals or groups to ensure that they understand the information and the message.
- Demonstrated ability to communicate information to individuals or groups; delivers presentations suited to the characteristics and needs of the audience.
- Proven ability to work with foreign security forces.
- Extensive overseas experience in Afghanistan, Ukraine, Republic of Korea, and Germany.
- Proven ability to apply the Army planning process military decision making, course of action development and analysis.
- Strong set of IT skills to include Microsoft Office, computer networking, and system administration.
- Follow Me scenario development, exercise design, and integration
- Decisive Action scenario development, exercise design, and integration
- Experience with Systems Approach to Training (SAT)
- Experience with Outcomes Based Training and Education (OBT&E)
- Tactical Decision Making & Problem Solving
- Small Unit Tactics
- Classroom Instruction
- Written Evaluations and Assessments
- Report, and Evaluation Writing
- Briefings and Presentations
- Computer Network Administration
- Curriculum Development at West Point and the Ground Forces Academy Odessa Ukraine

** WARCEN
 Serves as the WARCEN Manager in the Department of Military Instruction. Integrated the use of simulations for three military science courses, one college major (Defense Strategic Studies), and two leadership courses for the academic department Behavioral Science and Leadership.  Responsible for curriculum development in support of the military science curriculum.  Responsible for teaching tactical decision-making and problem solving in support of the basic officer leadership course.  Responsible for all WARCEN activities in support of academy functions to include VIP visits, recruitment, and education.

 Provided curriculum development for tactical decision-making and problem solving.

 Conducted tactical decision exercises in support of first through fourth year military science education and training.

 Initiate and adjudicate personnel security investigations, review national security clearances and special accesses, and ensure compliance with Executive Orders, the Office of Personnel Management (OPM) and Department of Commerce policies and procedural requirements;

 Develop, implement and revise security policies, procedures, standards and regulations for multiple security programs;

 Provide direction, guidance and management in support of Office of Security programs; Coordinate program support for several field security disciplines, including personnel security, information security, communications security and physical security in cooperation with other Office of Security offices and
 divisions; Develop security plans and coordinate security projects; and Interact and collaborate with other Departmental program offices as well as other Agencies regarding security matters.

** Recruiting
   Establishes and maintains contacts

   - Contacts, interviews, and advises civilian personnel to obtain qualified
   applicants for enlistment into the Army.

   - Contacts representatives of schools, public officials, personnel managers, parents of prospective applicants, religious and civil leaders, and others to present the Army as an employment and career opportunity.

   -Presents formal and informal talks on advantages of
   the Army at civic and service organizations and student bodies.

   Advertising

   - Distributes and displays recruiting publicity material. Establishes liaison
   with local radio, television, and newspaper agencies.

   - Writes, edits, or presents recruiting material for use by local communications agencies.
   - Lends and exhibits motion pictures for civic, fraternal, and service organizations and educational institutions.

   Conducts interviews

   - Interviews and counsels prospective enlistees. Discusses individual aims and
   goals to include security, personal aptitudes, training opportunities, job
   satisfaction and stability, advancement, prestige, and military life.

   - Explains Army benefits including: medical care, dependent allowance, housing,
   reenlistment bonus, retirement program, military/civilian educational
   opportunities, travel, recreational benefits, and all similar programs.
   - Evaluates applicants' occupational, educational, and psychological background
   to determine Army programs with specific individual appeal.

   - Explains occupational and organizational structure of the Army to applicants, parents, and interested groups of individuals.

   Evaluates applicants

   - Administers and scores screening physical examination, and enlisted screening
   test of applicants and counsels with regard to reasonable occupational
   aspirations within the Army.

   - Counsels disqualified applicants. Assists in
   administration of Armed Services Vocational Battery (ASVAB) and explains
   results to school officials and students.

   Administration

   - Advises applicants of disqualification's which are waiverable and assists
   preparation of waiver application.

   - Gathers individual data and prepares forms
   and documents incident to enlistment processing. Arranges for transportation,
   meals, and lodging for applicants where required. Maintains prospect card
   files, school program folders, and prospecting lists.

   - Assists in market research and analysis of recruiting territory and makes appropriate recommendations to station commander.

** Human Resources
     - You will oversee and implement a comprehensive human resources and employee
     services program.

     - Ensures development of local policies, goals and objectives
     for all managed human resources and employee service programs.

     - Advises on recruitment and placement strategies, development and implementation of
     workforce development and training plans, labor and management employee
     relations, classification program administration, military personnel program
     issues, adult continuing education matters, substance abuse policies, risk
     reduction and well being issues.

     - Plans, coordinates and provides direction for
     conducting comprehensive management studies.

     - Serves as the senior representative for installation operations matters with regard to OPM and
     Congressional representatives.

     - Exercises personnel management responsibilities.

     - Assigns, directs, reviews and evaluates work.

     - Establishes workload priorities.

     - Evaluates the performance of employees.

     - Exercises a full range of supervisory duties for a staff of four.

     - Serves as the principle financial advisor for the Administrative
     Section at BIA-NIFC.

     - Primary contact to provide Congressional, Departmental, Bureau and tribal
     administrative and management principles, guidance, policies and advises the
     Deputy Director and Director.

     - Responsible for the oversight of the BIA-NIFC Fire management procurement
     activities and functions.

     - Leads and coordinates the BIA interagency emergency incident business program.

** Equal Opportinity
   EQUAL OPPORTUNITY In the Army I was responsible for the Equal Opportunity


   Responsible for all digital system training and education, in addition to scenario design and exercise execution.  Reviewed and evaluated training simulations, gaming, and collective training programs, related to evolving battle command training simulations and the attainment of CGSC educational objectives.  Participates in comprehensive studies to identify and propose solutions to simulations model deficiencies. Gathers data and recommends programming code changes to modify simulation parameters.

   My Duties and Responsibilities

   - Conducts analytical studies and recommends procedures for the use of Army training simulations, Joint DoD simulations; and Commercial-off-the-Shelf
   (COTS) simulations and games that might be designated for integration within
   the college to support CGSC curriculum development and execution.


   - Represents the CGSC in meetings and forums with simulation development contractors for adapting code to improve existing models, to explore/develop requirements for a new model/ simulation, or to create training federation to support emerging CGSC requirements.

   - Participates in comprehensive studies to identify and propose solutions to simulations model deficiencies. Gathers data and recommends programming code changes to modify simulation parameters.

   - Reviewed and evaluated training simulations, gaming, and collective training programs, related to evolving battle command training simulations and theattainment of CGSC educational objectives.

       - Identified database requirements, assess future needs for the selected model,
        interface and develops and maintains program plans.

       - Provides simulation/federation expertise to build and edit unit and parameter databases for (OneSAF) and Entity Resolution Federation (ERF).

       - Assists in the planning and coordinating of VV&A activities. Reviews weapon
       performance data and ensures its incorporation into the federation and
       selected model databases.

       - Ensures the proper database integration within the federation.

       - Implemented Army Simulation training plans, directives and procedures,
       reports and studies for active Army training of units.

       - Plans, oversees, assigns and evaluates work of subordinates.

       - Hears and resolves group grievances or employee complaints; reviews and
       approves disciplinary actions.

       - Manages and oversees coordination for individual professional training,
       service school courses, quota allocations, and attendance.

       - Monitored, reviewed and assessed training support technology trends and program
       developments for new or modified requirements and adaptability to current and
       planned infrastructure and programs.


* Employment
** Alion Science and Technology
1750 Tysons Boulevard Suite 1300 McLean, VA 22102
703.918.4480

Sr. Curriculum Developer
July 2014 - Present

Design and develop a NATO based operations curriculum in support of Professional Military Education (PME) reform for the armed forces of the Ukraine.  Responsible for integrating that program of instruction into the Land Forces Academy curriculum.  Responsible for teaching 1st through 4th year cadets. Responsible for the integration of the Follow Me and Battle Command simulation software. Develop and train academy instructors on how to teach a NATO based  program of instruction.

Responsible for training cadets on small unit tactics, tactical decision-making, and NATO operations.  Teach 4th year cadets the military decision making process and course of action development.  Train and mentor the Ukrainian instructors in planning, and developing curriculum, and how to teach the NATO curriculum.

- Wrote the scenario, and developed the content for the February 2014 Captains Advance
Course
- Redesigned the platoon offense and defense scenarios for Follow Me
- Taught tactical decision making and small unit tactics to 2nd, 3rd, and 4th year cadets using Folloe Me.
- Taught squad and platoon battle drills react to contact, react to IED, and react to ambush to 1st through 4th year cadets
- Provided instruction on offensive and defensive small unit operations
- Provided instruction on information security, force protection, and anti-terrorist
operations
- Conducted digital AARs using the Follow Me simulation
- Manage a classroom of 20-30 students
- Provide records and reports to the commanding general of the Odessa Academy Major General Gulayk
- Keep records pertaining to student performance, discipline, testing, evaluation, and grades.
- Develop course content in support of military science
- Coordinate with host nation academic boards and certification
- Conduct annual reviews of NATO based military science curriculum

- Taught military decision making and course of action development to 20 captains during the FEB 2014 Captains Advance Course.
- Taught after action reviews to 50 1st and 2nd year cadets.
- Taught a professional development class to General Gulayk and his staff on curriculum development, instructor selection, and academic assessment.

Support of Professional Military Education (PME) Reform and Curriculum Development (CD) for the Armed Forces of the Ukraine

Taught tactical decision-making to 2nd, 3rd, and 4th year cadets using Follow Me.
Developed the simulation portion of the program of instruction for the February 2014 Captains Advanced Course.
Taught 1st through 4th year cadets using NATO-based program of instruction.
Advised Major General Gulayk on how to integrate our program of instruction into the academic year 2015 curriculum.

** DynCorp International FZ

1700 Old Meadow Road McLean, VA 22102
(571) 722-0210

Embedded Police Mentor
June 2011 - June 2013
Responsible for providing civilian law enforcement expertise to U.S. Department of State and Department of Defense mission in Afghanistan. Responsible for monitoring police conduct in the field. Partner with U.S. military counterparts to assess, mentor, and advise the Afghan National Police.  Responsible for training elements of the Afghan National Police in basic knowledge of law enforcement, human rights and community based policing.

- Trained as a personal security detail team member (Executive Protection/Bodyguard)
- Participated in over 80 foot patrols, and 100 convoy operations with the US Army and Afghan National Police
- Facilitated, coached, and mentored the planning and execution of combat patrols, and criminal investigations for a 10-man Afghan police unit.
- Instructed a number of courses focused on small unit tactics, intelligence operations, marksmanship, patrolling, battle drills, physicalsecurity, force protection, and mission planning.
- Trained and mentored a special unit of 10 AUP tasked with augmenting coalition forces and securing FOB Salerno
- Trained, mentored, and advised three Afghan Uniform Police Checkpoints totaling 5 officers, 15 NCOs, and 50 enlisted patrolmen
- Trained, mentored, and advised one Afghan Uniform Police Substation totaling 2 officers, 6 NCOs, 28 enlisted patrolmen

** United States Military Academy
West Point,NY 96930

Warfighting Simulation Center Manager
August 2004 - June 2011
Serves as the WARCEN Manager in the Department of Military Instruction. Responsible for curriculum development in support of the military science curriculum.  Teach tactical decision-making and problem solving to 1st through 4th year cadets.  Integrate the use of simulations into the military science curriculum. Provide support to the Defense Strategic Studies major, and the PL100 leadership course for the Behavioral Science and Leadership department.  Responsible for over $500,000 worth of equipment and software.  Responsible for all WARCEN activities in support of academy functions to include VIP visits, recruitment, and education.

+ Provided curriculum development to the department of military instructions tactical decision-making curriculum
+ Provided weapons training to over 7000 cadets
+ Taught the military decision making process to 30 4th year Defense Strategic Studies cadets.
+ Applied the Outcomes Based Training and Education model to all curriculum development
+ Integrated the Follow Me simulation into three military science courses, one college major (Defense Strategic Studies), and two leadership courses for the academic department Behavioral Science and Leadership.
+ Converted paper-based tactical decision games to digital content for use in the Follow Me simulation.
+ Consulted with developer regarding features and capabilities for Crucible of Command.

** Northrop Grumman
 DLDC,Lewis and Clark Bldg, Fort Leavenworth, KS 66027


 Simulations Specialist
 November 2001 - August 2004
 Responsible for all digital system training and education, in addition to scenario design and exercise execution.  Reviewed and evaluated training simulations, gaming, and collective training programs, related to evolving battle command training simulations and the attainment of CGSC educational objectives.  Participates in comprehensive studies to identify and propose solutions to simulations model deficiencies. Gathers data and recommends programming code changes to modify simulation parameters.

 - Integrated the use of low-overhead simulations into CGSOC/ILE curriculum.
 - Created the scenario, order of battle, digital maps, and events list for the division level GAAT exercise.
 - Conducted IPR briefings to Senior Retired Officers in support of the Prairie Warrior Capstone Exercise.
 - Reviewed and evaluated training simulations, gaming, and collective training
 programs, related to evolving battle command training simulations and the
 attainment of CGSC educational objectives.

 Integrated the use of low-overhead simulations such as Decisive Action and TacOpsCav into the Command and General Staff Officers Course.
 Created digital content for the Decisive Action simulation software for use in the Division
 GAAT exercise.
 Provided technical support for Decisive Action to 16 staff-groups running a Division level exercise.

** Battalion S-2
Fort Bragg, NC 28307

Organization Intel and Security Staff Leader
August 1999 - December 2001

Responsible for initiating, reviewing, and processing security clearances. Conduct annual and quarterly classes on anti-terrorism, physical security, and force protection.  Develop security plans for offices, arms rooms, and unit areas.  Provide tactical guidance to the senior commander in regards to enemy threat and situation.

Responsible for initiating, reviewing, and processing security clearances. Conduct annual and quarterly classes on anti-terrorism, physical security, and force protection.  Develop security plans for offices, arms rooms, and unit areas.  Provide tactical guidance to the senior commander in regards to enemy threat and situation.


- Conducted unit level anti-terrorism training for a 500 man organization.
- Established and wrote the security program for a 500 man organization.
- Evaluated unit force protection readiness and security.
- Conducted physical security and force protection inspections.
- Routinely conducted risk analysis in regards to communications, data, and physical security.
- Conducted routine investigations on personnel to determine security clearance status.
- Conducted briefings to the senior commander and staff in regards to security posture.

- Was the senior enlisted intel leader during operations planning for the exercise Purple Dragon.
- Provided train the trainer instruction for force protection, and physical security
- Develop the standard operating procedures for all intel section activities in garrison and during operations

** Platoon Sergeant
C 3-27 FAR (MLRS)
Fort Bragg, NC

Senior Enlisted Supervisor
June 1995 - August 1998

Responsible for the training, welfare, and leadership for 12 soldiers, 9 enlisted leaders, and one officer.  Responsible for the planning, preparation, and execution of collective training activities of the platoon. Maintains and processes operations and intelligence information to include situation maps. Supervises the preparation and distribution of maps, operational information, and status reports. Develops and maintains external and internal SOPs. Organizes force protection and security procedures for the platoon.

- Recognized by the brigade commander as one of the best platoon sergeants in the brigade, awarded an impact ARCOM
- Trained and mentored 1 Officer, 8 NCOs, and 20 Enlisted soldiers
- Supervised the everyday activities of 28 soldiers.
- Developed a platoon training plan for individual, section, and platoon collective tasks.
- Develop the platoon tactical standard operating procedures for field operations.

MLRS Platoon Sergeant
- Assists platoon leader in the planning, preparation, and execution of collective training activities of the platoon.
- Maintains and processes operations and intelligence information to include situation maps.
- Supervises the preparation and distribution of maps, operational information, and status reports.
- Develops and maintains external and internal SOPs. Organizes platoon defense.
- Presents briefings on current platoon operations and situation.
- Supervises platoon headquarters personnel including assignment of duties.
- Assumes duties of platoon leader in his absence.
- Conducts reconnaissance of platoon positions, reload points, and platoon area survey points.
- Supervises operator and organizational maintenance of equipment, vehicles, weapons, and communication and speech secure equipment.
- Leads in the operation of the PLDMD.
- Supervises the emplacement and march order of platoon elements. Supervises and directs convoy movement of ammunition resupply vehicles.
- Responsible for the receipt, accountability, distribution, and storage of ammunition.
- Plans and selects reload points, launch areas, and ammunition cache sites.
- Monitors platoon fire missions, launcher status, and logistic requirements.
- Coordinates positioning of platoon elements with maneuver and support elements.
- Conducts reconnaissance and selects routes between the Ammunition Transfer Point and Ammunition Supply Point.
- Coordinates with ammunition officer for location of transfer points, amount, and mix of ammunition.
** Monitoring Officer
- Gather information and report on the security situation and establish and report facts in reponse to specific incidents including those concerning alleged violations of fundamental OSCE principles in accordance with the PC decision 1117
- Conduct at least one or two patrols a week depending OPS workload.
- Submit an input for the daily report to the reporting officer after each patrol by no later than 1700hrs that day.
- Write at least two thematic weekly reports for the team.
- The day following the patrol, work with the reporting officer to clarify any additional information requests from the head office.
- Prepare a patrol report within 48 hours following each patrol, submit it to the other members of the patrol for verification and feedback, and then circulate to team
- Conduct quarterly interviews with veteran's and ATO participants regarding medical and mental health services.
- Write at least one thematic report dealing with veteran's issues.
- Interview NGOs that provide support services to ATO and veteran's.
- Interview government officials at the regional level who are responsible for dealing with veteran's issues.
- Create operational plans or courses of action in accordance with the Team Leader's guidance and the mission mandate.
- Conduct risk assessments for potentially hazardous patrols such as the 2nd of May anniversary, or trips to the Transnistrian Border.
- Manage the patrol schedule, leaves, and time-off for the language assistants.
- Allocate team resources such as cash, vehicles, and personnel for daily operations.
- Track the status of personnel on a daily basis and keep track of future absences such as leaves or temporary duty.




























           Chapter 8
           References
           Donald Vandergriff
           DynCorp International
           Chief COMIJC Fusion Cell
           Cell: (571)723-6202
           Vandergriffdonald@usa.net

           James Vizzard
           Deputy Chief of Staff - Plans, and Strategy Office of the Chief of Legislative Liaison
           LTC
           (571)-969-1693
           James.vizzard@gmail.com

           James Lunsford
           Decisive Point
           President
           Office: (816)-584-2882
           jim@decisive-point.com

           Harry Thompson
           Alion Science and Technology
           Vice President for Program Management
           Cell: (912) 293-6454
           HThompson@alionscience.com

           Jeff Leser
           Deputy Director DLDC
           jeffrey.w.leser.civ@mail.mil
           (913)-684-3045

           Stephen Banks
           Major, USA
           stephen.j.banks.mil@mail.mil





























           Chapter 9
           Active
           Vincent R. Taijeron
           22 French Blvd Apt 20, Odessa, Ukraine 65000
           (38) 099 529-0612
           vincent.taijeron@gmail.com


           #
           - Over 30 years' experience providing force protection, physical security, and combat operations.
           - Secret Security Clearance (Security review 2014).
           - Proven ability to operate in dynamic volatile environments while under pressure.
           - Experience with Systems Approach to Training (SAT).
           - Classroom Instruction and curriculum development.
           - Proven ability to clearly and concisely convey written information orally and/or in writing to individuals or groups to ensure that they understand the information and the message.
           - Demonstrated ability to communicate information to individuals or groups; delivers presentations suited to the characteristics and needs of the audience.
           - Strong set of IT skills to include Microsoft Office, computer networking, and system administration.








































           Chapter 10
           Employment
           Alion Science and Technology
           1750 Tysons Boulevard Suite 1300 McLean, VA 22102
           703.918.4480

           Sr. Curriculum Developer
           July 2014 - Present
           Design, Develop, Implement, and Evaluate training products to train Ukrainian cadets on
           NATO Compatible small unit tactics, tactical decision making, and problem solving.
           Train Ukrainian instructors to accomplish the implementation of training.  Field and train
           using the Follow Me and Battle Command simulations.

           - Redesigned the platoon offense and defense scenarios for Follow Me
           - Taught tactical decision making and small unit tactics to 2nd, 3rd, and 4th year cadets
           - Taught squad and platoon battle drills react to contact, react to IED, and react to ambush to 1st through 4th year cadets
           - Provided instruction on offensive and defensive small unit operations
           - Provided instruction on information security, force protection, and anti-terrorist
           operations
           - Manage a classroom of 20-30 students
           - Provide records and reports to the commanding general of the Odessa Academy Major General Gulayk
           - Keep records pertaining to student performance, discipline, testing, evaluation, and grades.
           - Develop curriculum tailored to the Odessa military academy
           - Coordinate with host nation academic boards and certification
           - Conduct annual reviews of NATO based military science curriculum


           #
           DynCorp International FZ
           1700 Old Meadow Road McLean, VA 22102
           (571) 722-0210

           Embedded Police Mentor
           June 2011 - June 2013
           Responsible for training elements of the Afghan National Police in basic knowledge of law
           enforcement and human rights and mentoring police
           officers and leaders to instill a culture of service to the people of Afghanistan.

           - Facilitated, coached, and mentored the planning and execution of combat patrols, and
           criminal investigations for a 10-man Afghan police unit.
           - Instructed a number of courses focused on small unit tactics, intelligence operations,
           marksmanship, patrolling, battle drills, physical security, force protection, and mission
           planning.
           - Trained and mentored a special unit of 10 AUP tasked with augmenting coalition forces
           and securing FOB Salerno
           - Trained, mentored, and advised three Afghan Uniform Police checkpoints totaling
           5 officers, 15 NCOs, and 50 enlisted patrolmen
           - Trained, mentored, and advised one Afghan Uniform Police Substation totaling 2
           officers, 6 NCOs, 28 enlisted patrolmen

           #
           United States Military Academy
           West Point,NY 96930

           Warfighting Simulation Center Manager
           August 2004 - June 2011
           Serves as the WARCEN Manager in the Department of Military Instruction. Integrated the use of simulations for three military science courses, one college major (Defense Strategic Studies), and two leadership courses for the academic department Behavioral Science and Leadership.

           - Provided curriculum development to the department of military instructions tactical decision-making block on instruction.
           - Wrote the simulation integration plan for the military science curriculum covering 1st-4th year cadets.
           - Provided weapons training to over 7000 cadets
           - Taught small unit tactics and force protection to over 3000 cadets
           - Developed and created the scenario for the Defense Strategic Studies (college major) Capstone Exercise, to  include maps, events list, and roleplaying scripts.
           - Conducted regular briefings in reagards to WARCEN support of military education, to the Commandant, Superintendent, Political, and Academic VIPs.


           #
           Northrop Grumman
           DLDC,Lewis and Clark Bldg, Fort Leavenworth, KS 66027


           Simulations Specialist
           November 2001 - August 2004
           Original member of the Digital Leader Development (DLDC) Simulations Team.  Responsible for all digital system training and education, in
           addition to scenario design and exercise execution of Brigade through Corps level operations.

           - Integrated the use of low-overhead simulations into CGSOC/ILE curriculum.
           - Created the scenario, order of battle, digital maps, and events list for the division level GAAT exercise.
           - Provided IPR briefings to Senior Retired Officers in support of the Prairie Warrior Capstone Exercise.
           - Reviewed and evaluated training simulations, gaming, and collective training
           programs, related to evolving battle command training simulations and the
           attainment of CGSC educational objectives.

           #
           US Army
           Fort Bragg, NC 28307

           Organization Intel and Security Staff Leader
           August 1999 - December 2001

           Primary staff enlisted leader for Intel and security.  Responsible for initiating, reviewing, and processing security clearances. Conduct annual and quarterly classes on anti-terrorism, physical security, and force protection.  Develop security plans for offices, arms rooms, and unit areas.  Provide tactical guidance to the senior commander in regards to enemy threat and situation.

           - Conducted unit level anti-terrorism training for a 500 man organization.
           - Established and wrote the security program for a 500 man organization.
           - Evaluated unit force protection readiness and security.
           - Conducted physical security and force protection inspections.
           - Routinely conducted risk analysis in regards to communications, data, and physical security.
           - Conducted routine investigations on personnel to determine security clearance status.
           - Conducted briefings to the senior commander and staff in regards to security posture.



























           Chapter 11
           Education
           University of Guam
           Batchelors
           English
           1981-1986

           Guam Community College
           Associates
           Technical Electronics
           1978-1981

           Advanced Leaders Course, - 1997
           Basic Leaders Course - 1992
           Primary Leaders Course - 1983
           #
           - DynCorp International Personal Security Detail Course
           - DynCorp International Personal Security Transport Course
           - International Instructor Certification
           - Range Safety Officer Certification
           - Combat Life Saver
           - Annual qualification with the M4, M240B, M249, and M9
           #
           Donald Vandergriff
           DynCorp International
           Chief COMIJC Fusion Cell
           Cell: (571)723-6202
           Vandergriffdonald@usa.net

           Harry Thompson
           Alion Science and Technology
           Vice President for Program Management
           Cell: (912) 293-6454
           HThompson@alionscience.com

           James Lunsford
           Decisive Point
           President
           Office: (816)-584-2882
           jim@decisive-point.com

           #
           Vincent R. Taijeron
           22 French Blvd Apt 20, Odessa, Ukraine 65000
           (38) 099 529-0612
           vincent.taijeron@gmail.com

           Passport: 464063378
           Expires: 29 SEP 2020

           #
           SKILLS AND CLEARANCE
           - Secret Security Clearance (Security review 2014)

           - Proven ability to operate in dynamic volatile environments while under pressure

           - Over 30 years' experience providing force protection, physical security, and combat
           Operations

           - Proven ability to clearly and concisely convey written information orally and/or in writing
           to individuals or groups to ensure that they understand the information and the message.

           - Demonstrated ability to communicate information to individuals or groups; delivers
           presentations suited to the characteristics and needs of the audience.

           - Strong set of IT skills to include Microsoft Office, computer networking, and system
           administration.



           #
           Alion Science and Technology
           1750 Tysons Boulevard Suite 1300 McLean, VA 22102
           703.918.4480

           Sr. Curriculum Developer
           July 2014 - Present
           Design, Develop, Implement, and Evaluate training products to train Ukrainian cadets on
           NATO Compatible small unit tactics, tactical decision making, and problem solving.
           Train Ukrainian instructors to accomplish the implementation of training.  Field and train
           using the Follow Me and Battle Command simulations.

           - Wrote the scenario, and developed the content for the February 2014 Captains Advance
           Course
           - Redesigned the platoon offense and defense scenarios for Follow Me
           - Taught tactical decision making to 2nd, 3rd, and 4th year cadets
           - Taught battle drills react to contact, react to IED, and react to ambush
           - Provided instruction on offensive and defensive small unit operations
           - Provided instruction on information security, force protection, and anti-terrorist
           operations
           - Conducted digital AARs using the Follow Me simulation

           #
           DynCorp International FZ
           1700 Old Meadow Road McLean, VA 22102
           (571) 722-0210

           Embedded Police Mentor
           June 2011 - June 2013
           Responsible for training elements of the Afghan National Police in basic knowledge of law
           enforcement and human rights and mentoring police
           officers and leaders to instill a culture of service to the people of Afghanistan.

           - Developed the force protection security plan for two police checkpoints
           - Trained as a personal security detail team member (Executive Protection/Bodyguard)
           - Participated in over 80 foot patrols, and 100 convoy operations with the US Army and
           Afghan National Police
           - Facilitated, coached, and mentored the planning and execution independent combat
           patrols, intelligence gathering, criminal investigations for a 10-man Afghan police unit.

           - Instructed a number of courses focused on small unit tactics, intelligence operations,
           marksmanship, patrolling, battle drills, physicalsecurity, force protection, and mission
           planning.
           - Trained and mentored a special unit of 10 AUP tasked with augmenting coalition forces
           and securing FOB Salerno
           - Facilitated, coached, and mentored the planning and execution independent combat
           patrols, intelligence gathering, criminal investigations for a 10-man Afghan police unit.
           - Trained and mentored over 80 patrolmen, 3 officers, and 10 enlisted leaders

           #
           United States Military Academy
           West Point,NY 96930

           Warfighting Simulation Center Manager
           August 2004 - June 2011
           Serves as the WARCEN Manager in the Department of Military Instruction. Integrated the use of simulations for three military science courses, one college major (Defense Strategic Studies), and two leadership courses for the academic department Behavioral Science and Leadership.

           - Provided weapons training to over 7000 cadets
           - Taught small unit tactics and force protection to over 3000 cadets
           - Integrated the use of low-overhead simulations to support the instruction of small unit tactical decision making and problem solving.
           - Developed scenarios, exercise content, and supporting documentation for the GEN Frederick Franks
           leadership exercise
           - Developed and created the scenario for the Defense Strategic Studies (college major) Capstone Exercise, to  include maps, events list, and roleplaying scripts.
           - Conducted regular briefings in reagards to WARCEN support of military education, to the Commandant, Superintendent, Political, and Academic VIPs.


           #
           Northrop Grumman
           DLDC,Lewis and Clark Bldg, Fort Leavenworth, KS 66027


           Simulations Specialist
           November 2001 - August 2004
           Original member of the Digital Leader Development (DLDC) Simulations Team.  Responsible for all digital system training and education, in
           addition to scenario design and exercise execution of Brigade through Corps level operations.

           - Integrated the use of low-overhead simulations into CGSOC/ILE curriculum.
           - Created the scenario, order of battle, digital maps, and events list for the division level GAAT exercise.
           - Provided IPR briefings to Senior Retired Officers in support of the Prairie Warrior Capstone Exercise.
           - Reviewed and evaluated training simulations, gaming, and collective training
           programs, related to evolving battle command training simulations and the
           attainment of CGSC educational objectives.

           #
           US Army
           Fort Bragg, NC 28307

           Organization Intel and Security Staff Leader
           August 1999 - December 2001

           Primary staff enlisted leader for Intel and security.  Responsible for initiating, reviewing, and processing security clearances. Conduct annual and quarterly classes on anti-terrorism, physical security, and force protection.  Develop security plans for offices, arms rooms, and unit areas.  Provide tactical guidance to the senior commander in regards to enemy threat and situation.

           - Conducted unit level anti-terrorism training for a 500 man organization.
           - Established and wrote the security program for a 500 man organization.
           - Evaluated unit force protection readiness and security.
           - Conducted physical security and force protection inspections.
           - Routinely conducted risk analysis in regards to communications, data, and physical security.
           - Conducted routine investigations on personnel to determine security clearance status.
           - Conducted briefings to the senior commander and staff in regards to security posture.
           #
           CERTIFICATIONS AND TRAINING

           - DynCorp International Personal Security Detail Course
           - DynCorp International Personal Security Transport Course
           - International Instructor Certification
           - Range Safety Officer Certification
           - Combat Life Saver
           - Annual qualification with the M4, M240B, M249, and M9
           #
           EDUCATION

           University of Guam
           Batchelors
           English
           1981-1986

           Guam Community College
           Associates
           Technical Electronics
           1978-1981

           Advanced Leaders Course, - 1997
           Basic Leaders Course - 1992
           Primary Leaders Course - 1983
           #
           REFERENCES

           Donald Vandergriff
           DynCorp International
           Chief COMIJC Fusion Cell
           Cell: (571)723-6202
           Vandergriffdonald@usa.net

           Harry Thompson
           Alion Science and Technology
           Vice President for Program Management
           Cell: (912) 293-6454
           HThompson@alionscience.com

           James Lunsford
           Decisive Point
           President
           Office: (816)-584-2882
           jim@decisive-point.com




* Education
University of Guam
Batchelors
English
1981-1986

Guam Community College
Associates
Technical Electronics
1978-1981

Advanced Leaders Course, - 1997
Basic Leaders Course - 1992
Primary Leaders Course - 1983

Dyncorp
- DynCorp International Personal Security Detail Course
- DynCorp International Personal Security Transport Course
- International Instructor Certification
- Range Safety Officer Certification
- Combat Life Saver
- Annual qualification with the M4, M240B, M249, and M9


* References
 Donald Vandergriff
 DynCorp International
 Chief COMIJC Fusion Cell
 Cell: (571)723-6202
 Vandergriffdonald@usa.net

 Harry Thompson
 Alion Science and Technology
 Vice President for Program Management
 Cell: (912) 293-6454
 HThompson@alionscience.com

 James Lunsford
 Decisive Point
 President
 Office: (816)-584-2882
 jim@decisive-point.com

* Submitted
** Submitted 1
Vincent R. Taijeron
22 French Blvd Apt 20, Odessa, Ukraine 65000
(38) 099 529-0612
vincent.taijeron@gmail.com
*** SKILLS AND KNOWLEDGE
- Over 30 years' experience providing force protection, physical security, and combat operations
- Proven ability to clearly and concisely convey written information orally and/or in writing to individuals or groups to ensure that they understand the information and the message.
- Demonstrated ability to communicate information to individuals or groups; delivers presentations suited to the characteristics and needs of the audience.
- Extensive overseas experience in Afghanistan, Ukraine, Republic of Korea, and Germany.
- Experience with Systems Approach to Training (SAT) and Outcomes Based Education
- Strong set of IT skills to include Microsoft Office, computer networking, and system administration.

*** Employment
**** Alion Science and Technology
1750 Tysons Boulevard Suite 1300 McLean, VA 22102
703.918.4480

Sr. Curriculum Developer
July 2014 - Present
Design, develop, implement, and evaluate curriculum in support of NATO based operations.  Responsible for training cadets on small unit tactics, tactical decision-making, and NATO operations.  Teach 4th year cadets the military decision making process and course of action development.  Train and mentor the Ukrainian instructors in planning, and developing curriculum, and teaching the NATO curriculum.

- Taught military decision-making and course of action development to 20 captains during the FEB 2014 Captains Advance Course.
- Taught a professional development class to General Gulayk and his staff on curriculum development, instructor selection, and academic assessment.
- Provide records and reports to the commanding general of the Odessa Academy Major General Gulayk
- Keep records pertaining to student performance, discipline, testing, and evaluation.
- Develop course content in support of military science
- Conduct annual reviews of NATO based military science curriculum

**** DynCorp International FZ
1700 Old Meadow Road McLean, VA 22102
(571) 722-0210

Embedded Police Mentor
June 2011 - June 2013
Responsible for training elements of the Afghan National Police in basic knowledge of law enforcement and human rights and mentoring police officers and leaders to instill a culture of service to the people of Afghanistan.

- Trained and mentored a special unit of 10 AUP tasked with augmenting coalition forces and securing FOB Salerno
- Trained, mentored, and advised three Afghan Uniform Police Checkpoints totaling 5 officers, 15 NCOs, and 50 enlisted patrolmen
- Trained, mentored, and advised one Afghan Uniform Police Substation totaling 2 officers, 6 NCOs, 28 enlisted patrolmen
- Instructed a number of courses focused on small unit tactics, intelligence operations, marksmanship, patrolling, battle drills, physical security, force protection, and mission planning.

**** United States Military Academy
West Point, NY 96930

Warfighting Simulation Center Manager
August 2004 - June 2011
Serves as the WARCEN Manager in the Department of Military Instruction. Integrated the use of simulations for three military science courses, one college major (Defense Strategic Studies), and two leadership courses for the academic department Behavioral Science and Leadership.

- Taught the military decision making process to 30 4th year Defense Strategic Studies cadets.
- Applied the Outcomes Based Training and Education model to all curriculum development.
- Provided curriculum development to the department of military instructions tactical decision-making curriculum.
- Developed scenarios, exercise content, and supporting documentation for the GEN Frederick Franks leadership exercise.
- Conducted regular briefings in regards to WARCEN support of military education, to the Commandant, Superintendent, Political, and Academic VIPs.

**** Northrop Grumman
Command and General Staff College
DLDC, Lewis and Clark Bldg, Fort Leavenworth, KS 66027

Simulations Specialist
November 2001 - August 2004
Original member of the Digital Leader Development (DLDC) Simulations Team.  Responsible for all digital system training and education, in addition to scenario design and exercise execution of Brigade through Corps level operations.

- Integrated the use of low-overhead simulations into CGSOC/ILE curriculum.
- Created the scenario, order of battle, digital maps, and events list for the division level GAAT exercise.
- Provided IPR briefings to Senior Retired Officers in support of the Prairie Warrior Capstone Exercise.
- Reviewed and evaluated training simulations, gaming, and collective training programs, related to evolving battle command training simulations and the attainment of CGSC educational objectives.

**** US Army
3-27 FAR (MLRS)
Fort Bragg, NC 28307

Battalion Intel NCO
August 1999 - December 2001

Primary staff enlisted leader for Intel and security.  Responsible for initiating, reviewing, and processing security clearances. Conduct annual and quarterly classes on anti-terrorism, physical security, and force protection.  Develop security plans for offices, arms rooms, and unit areas.  Provide tactical guidance to the senior commander in regards to enemy threat and situation.

- Was the senior enlisted intel leader during operations planning for the exercise Purple Dragon.
- Provided train the trainer instruction for force protection, and physical security
- Develop the standard operating procedures for all intel section activities in garrison and during operations
- Conducted unit level anti-terrorism training for a 500-man organization.
- Established and wrote the security program for a 500-man organization.
- Evaluated unit force protection readiness and security.
- Conducted physical security and force protection inspections.
- Routinely conducted risk analysis in regards to communications, data, and physical security.
- Conducted routine investigations on personnel to determine security clearance status.

**** US Army
C 3-27 FAR (MLRS)
Fort Bragg, NC 28307

Platoon Sergeant
June 1995 - August 1998

As a platoon sergeant I was the platoon's most experienced senior enlisted supervisor and second in command. I was responsible for the leadership, discipline, training, and welfare of a 25-person organization.  Responsible for planning and executing field operations.  Responsible for developing TACSOP, individual, section, and platoon training plans.

- Recognized by the brigade commander as one of the best platoon sergeants in the brigade, awarded an impact ARCOM
- Trained and mentored 1 Officer, 8 NCOs, and 20 enlisted soldiers
- Supervised the everyday activities of 28 soldiers.
- Developed a platoon-training plan for individual, section, and platoon collective tasks.
- Develop the platoon tactical standard operating procedures for field operations.

*** EDUCATION AND TRAINING

University of Guam
Bachelors
English
1981-1986

Guam Community College
Associates
Technical Electronics
1978-1981

Advanced Leaders Course, - 1997
Basic Leaders Course - 1992
Primary Leaders Course - 1983

- DynCorp International Personal Security Detail Course
- DynCorp International Personal Security Transport Course
- International Instructor Certification
- Range Safety Officer Certification
- Combat Life Saver
- Annual qualification with the M4, M240B, M249, and M9

*** REFERENCES
Donald Vandergriff
DynCorp International
Chief COMIJC Fusion Cell
Cell: (571)723-6202
Vandergriffdonald@usa.net

Harry Thompson
Alion Science and Technology
Vice President for Program Management
Cell: (912) 293-6454
HThompson@alionscience.com

James Lunsford
Decisive Point
President
Office: (816)-584-2882
jim@decisive-point.com

** Submitted 2
   Vincent R. Taijeron
   22 French Blvd Apt 20
   Odessa, Ukraine 65000
   (38) 099 529-0612
   vincent.taijeron@gmail.com

   SKILLS AND ABILITIES
   - Over 30 years' experience providing force protection, physical security, and combat operations.
   - Secret Security Clearance (Security review 2014).
   - Proven ability to operate in dynamic volatile environments while under pressure.
   - Experience with Systems Approach to Training (SAT).
   - Classroom Instruction and curriculum development.
   - Proven ability to clearly and concisely convey written information orally and/or in writing to individuals or groups to ensure that they understand the information and the message.
   - Demonstrated ability to communicate information to individuals or groups; delivers presentations suited to the characteristics and needs of the audience.
   - Strong set of IT skills to include Microsoft Office, computer networking, and system administration.

   EMPLOYMENT

   Alion Science and Technology
   1750 Tysons Boulevard Suite 1300 McLean, VA 22102
   703.918.4480

   Sr. Curriculum Developer
   July 2014 - Present
   Design, develop, implement, and evaluate curriculum in support of NATO based operations.  Responsible for training cadets on small unit tactics, tactical decision-making, and NATO operations.  Train Ukrainian instructors to teach the same curriculum.  Field and train using the Follow Me and Battle Command simulations.

   - Redesigned the platoon offense and defense scenarios for Follow Me
   - Taught tactical decision making and small unit tactics to 2nd, 3rd, and 4th year cadets
   - Taught squad and platoon battle drills react to contact, react to IED, and react to ambush to 1st through 4th year cadets
   - Provided instruction on offensive and defensive small unit operations
   - Provided instruction on information security, force protection, and anti-terrorist
   operations
   - Provide records and reports to the commanding general of the Odessa Academy Major General Gulayk
   - Keep records pertaining to student performance, discipline, testing, evaluation, and grades.
   - Develop curriculum tailored to the Odessa military academy
   - Coordinate with host nation academic boards and certification
   - Conduct annual reviews of NATO based military science curriculum

   DynCorp International FZ
   1700 Old Meadow Road McLean, VA 22102
   (571) 722-0210

   Embedded Police Mentor
   June 2011 - June 2013
   Responsible for training elements of the Afghan National Police in basic knowledge of law enforcement and human rights and mentoring police officers and leaders to instill a culture of service to the people of Afghanistan.

   - Facilitated, coached, and mentored the planning and execution of combat patrols, and
   criminal investigations for a 10-man Afghan police unit.
   - Instructed a number of courses focused on small unit tactics, intelligence operations,
   marksmanship, patrolling, battle drills, physical security, force protection, and mission
   planning.
   - Trained and mentored a special unit of 10 AUP tasked with augmenting coalition forces
   and securing FOB Salerno
   - Trained, mentored, and advised three Afghan Uniform Police checkpoints totaling
   5 officers, 15 NCOs, and 50 enlisted patrolmen
   - Trained, mentored, and advised one Afghan Uniform Police Substation totaling 2
   officers, 6 NCOs, 28 enlisted patrolmen


   United States Military Academy
   West Point,NY 96930

   Warfighting Simulation Center Manager
   August 2004 - June 2011
   Serves as the WARCEN Manager in the Department of Military Instruction. Integrated the use of simulations for three military science courses, one college major (Defense Strategic Studies), and two leadership courses for the academic department Behavioral Science and Leadership.

   - Provided curriculum development to the department of military instructions tactical decision-making block on instruction.
   - Wrote the simulation integration plan for the military science curriculum covering 1st-4th year cadets.
   - Provided weapons training to over 7000 cadets
   - Taught small unit tactics and force protection to over 3000 cadets
   - Developed and created the scenario for the Defense Strategic Studies (college major) Capstone Exercise, to  include maps, events list, and roleplaying scripts.
   - Conducted regular briefings in reagards to WARCEN support of military education, to the Commandant, Superintendent, Political, and Academic VIPs.

   Northrop Grumman
   DLDC,Lewis and Clark Bldg, Fort Leavenworth, KS 66027

   Simulations Specialist
   November 2001 - August 2004
   Original member of the Digital Leader Development (DLDC) Simulations Team.  Responsible for all digital system training and education, in
   addition to scenario design and exercise execution of Brigade through Corps level operations.

   - Integrated the use of low-overhead simulations into CGSOC/ILE curriculum.
   - Created the scenario, order of battle, digital maps, and events list for the division level GAAT exercise.
   - Provided IPR briefings to Senior Retired Officers in support of the Prairie Warrior Capstone Exercise.
   - Reviewed and evaluated training simulations, gaming, and collective training
   programs, related to evolving battle command training simulations and the
   attainment of CGSC educational objectives.


   US Army
   Fort Bragg, NC 28307

   Organization Intel and Security Staff Leader
   August 1999 - December 2001

   Primary staff enlisted leader for Intel and security.  Responsible for initiating, reviewing, and processing security clearances. Conduct annual and quarterly classes on anti-terrorism, physical security, and force protection.  Develop security plans for offices, arms rooms, and unit areas.  Provide tactical guidance to the senior commander in regards to enemy threat and situation.

   - Conducted unit level anti-terrorism training for a 500 man organization.
   - Established and wrote the security program for a 500 man organization.
   - Evaluated unit force protection readiness and security.
   - Conducted physical security and force protection inspections.
   - Routinely conducted risk analysis in regards to communications, data, and physical security.
   - Conducted routine investigations on personnel to determine security clearance status.
   - Conducted briefings to the senior commander and staff in regards to security posture.

   University of Guam
   Batchelors
   English
   1981-1986

   Guam Community College
   Associates
   Technical Electronics
   1978-1981

   Advanced Leaders Course, - 1997
   Basic Leaders Course - 1992
   Primary Leaders Course - 1983

   - DynCorp International Personal Security Detail Course
   - DynCorp International Personal Security Transport Course
   - International Instructor Certification
   - Range Safety Officer Certification
   - Combat Life Saver
   - Annual qualification with the M4, M240B, M249, and M9

   Donald Vandergriff
   DynCorp International
   Chief COMIJC Fusion Cell
   Cell: (571)723-6202
   Vandergriffdonald@usa.net

   Harry Thompson
   Alion Science and Technology
   Vice President for Program Management
   Cell: (912) 293-6454
   HThompson@alionscience.com

   James Lunsford
   Decisive Point
   President
   Office: (816)-584-2882
   jim@decisive-point.com

 #
 Vincent R. Taijeron
 22 French Blvd Apt 20, Odessa, Ukraine 65000
 (38) 099 529-0612
 vincent.taijeron@gmail.com


 SKILLS AND CLEARANCE
 - Secret Security Clearance (Security review 2014).
 - Proven ability to operate in dynamic volatile environments while under pressure.
 - Over 30 years' experience providing force protection, physical security, and combat operations.
 - Proven ability to clearly and concisely convey written information orally and/or in writing to individuals or groups to ensure that they understand the information and the message.
 - Demonstrated ability to communicate information to individuals or groups; delivers presentations suited to the characteristics and needs of the audience.
 - Strong set of IT skills to include Microsoft Office, computer networking, and system administration.

 EMPLOYMENT

 Alion Science and Technology
 1750 Tysons Boulevard Suite 1300 McLean, VA 22102
 (703)918-4480

 Sr. Curriculum Developer
 July 2014 - Present
 Design, Develop, Implement, and Evaluate training products to train Ukrainian cadets on NATO Compatible small unit tactics, tactical decision-making, and problem solving. Train Ukrainian instructors to accomplish the implementation of training.  Field and train using the Follow Me and Battle Command simulations.

 - Redesigned the platoon offense and defense scenarios for Follow Me.
 - Taught battle drills react to contact, react to IED, and react to ambush.
 - Provided instruction on offensive and defensive small unit operations
 - Provided instruction on information security, force protection, and anti-terrorist operations.

 DynCorp International FZ
 1700 Old Meadow Road McLean, VA 22102
 (571) 722-0210

 Embedded Police Mentor
 June 2011 - June 2013
 Responsible for training elements of the Afghan National Police in basic knowledge of law enforcement, human rights, and mentoring police officers and leaders to instill a culture of service to the people of Afghanistan.

 - Developed the force protection security plan for two police checkpoints, and one police sub-station.
 - Trained as a personal security detail team member (Executive Protection/Bodyguard)
 - Participated in over 80 foot patrols, and 100 convoy operations with the US Army and Afghan National Police.
 - Facilitated, coached, and mentored the planning and execution independent combat patrols, intelligence gathering, criminal investigations for a 10-man Afghan police unit.
 - Instructed a number of courses focused on small unit tactics, intelligence operations, marksmanship, patrolling, battle drills, physical security, force protection, and mission planning.
 - Trained and mentored over 80 patrolmen, 3 officers, and 10 enlisted leaders
 - Trained as a personal security detail team member (Executive Protection/Bodyguard)

 United States Military Academy
 West Point, NY 96930

 Warfighting Simulation Center Manager
 August 2004 - June 2011
 Serves as the WARCEN Manager in the Department of Military Instruction. Integrated the use of simulations for three military science courses, one college major (Defense Strategic Studies), and two leadership courses for the academic department Behavioral Science and Leadership.

 - Provided weapons training to over 7000 cadets
 - Taught small unit tactics and force protection to over 3000 cadets
 - Integrated the use of low-overhead simulations to support the instruction of small unit tactical decision making and problem solving.
 - Developed and created the scenario for the Defense Strategic Studies (college major) Capstone Exercise, to include maps, events list, and roleplaying scripts.
 - Conducted regular briefings in regards to WARCEN support of military education, to the Commandant, Superintendent, Political, and Academic VIPs.


 Northrop Grumman
 DLDC,Lewis and Clark Bldg, Fort Leavenworth, KS 66027

 Simulations Specialist
 November 2001 - August 2004
 Original member of the Digital Leader Development (DLDC) Simulations Team.  Responsible for all digital system training and education, in addition to scenario design and exercise execution of Brigade through Corps level operations.

 - Integrated the use of low-overhead simulations into CGSOC/ILE curriculum.
 - Created the scenario, order of battle, digital maps, and events list for the division level GAAT exercise.
 - Provided IPR briefings to Senior Retired Officers in support of the Prairie Warrior Capstone Exercise.
 - Reviewed and evaluated training simulations, gaming, and collective training programs, related to evolving battle command training simulations and the attainment of CGSC educational objectives.

 US Army
 Fort Bragg, NC 28307

 Organization Intel and Security Staff Leader
 August 1999 - December 2001
 Primary staff enlisted leader for Intel and security.  Responsible for initiating, reviewing, and processing security clearances. Conduct annual and quarterly classes on anti-terrorism, physical security, and force protection.  Develop security plans for offices, arms rooms, and unit areas.  Provide tactical guidance to the senior commander in regards to enemy threat and situation.

 - Conducted unit level anti-terrorism training for a 500-man organization.
 - Established and wrote the security program for a 500-man organization.
 - Evaluated unit force protection readiness and security.
 - Conducted physical security and force protection inspections.
 - Routinely conducted risk analysis in regards to communications, data, and physical security.
 - Conducted routine investigations on personnel to determine security clearance status.
 - Conducted briefings to the senior commander and staff in regards to security posture.

 CERTIFICATIONS AND TRAINING

 - DynCorp International Personal Security Detail Course
 - DynCorp International Personal Security Transport Course
 - International Instructor Certification
 - Range Safety Officer Certification
 - Annual qualification with the M4, M240B, M249, and M9


 EDUCATION

 University of Guam
 Bachelors
 English
 1981-1986

 Guam Community College
 Associates
 Technical Electronics
 1978-1981

 Advanced Leaders Course, - 1997
 Basic Leaders Course - 1992
 Primary Leaders Course - 1983
