#+TITLE: Modern Land Combat Commander
#+STARTUP: indent

* Introduction 
MLCC is a simulation of modern brigade/division level conflict between forces of
equal abilities.
 
* General Course of Play
MLCC is a two-player game.  Each player moves his units and executes attacks
on enemy units in turn, attempting to fulfill the conditions of victory.  To
move from one hex to another, each unit expends a portion of its movement
allowance.  Combat is resolved by comparing the total combat strength of
adjacent opposing units and expressing the comparison as a simplified
probability ratio (odds).  A dies is rolled and the outcome indicated on the
combat results table is applies to the units involved.

* Game Files
There are several game files that are required to play the game.
- Map image.  This is a simple jpg image that serves as a visual reference for
  the player.
- Map Terrain File.  This file defines the terrain for the map.
- Scenario file.  This file defines the operational environment for a specific
  scenario.
- Unit and game icons.  These files are png or jpg and depict units and other
  game functions.

* Map
- The game map is a 2d representation of a land-based area of operations.
- A hexagonal grid is superimposed upon the map image to control movement and
  combat of the units, tracing supply lines, and delineating the terrain imposed
  on the map.
** Requirements
- The image format for the map is jpg.
- Map colors to be determined.  Flashpoint Campaign values.
- Individual hex for the grid is 72 px tall with the flat side facing up.
- Size of the map can vary depending on the operations area.
*** Terrain File
The terrain file defines the terrain elements for a specific map.
- json format??
- Terrain movement costs (see terrain effects table).
- Combat modifiers.

* Units
- Icons use NATO symbols and represent different units from the opposing forces.
** Requirements
- The image format for unit and game icons is jpg or png.
- Texture map??
 
* Charts and Tables
* Scale
- Combat units represent battalions and brigades.
- Some combat such as Artillery or Air Defense may be represented by batterys or
  platoons.
- Hexes represent 5 to 10 kms on the ground.
- Each turn represents 3 to 6 hours of time.

* Scenario File
The scenario file defines the operational environment for the game.
- Orders of battle for both sides.  The order of battle specifies which units
  will be available for the scenario.
- Map image and corresponding terrain file.
- Weather conditions.
- Mission objectives.
- Operations order file.  This is a link to the OPORD briefing which provides
  the player with the information they need to plan their mission.
- json format?

* Sequence of Play
** The Game-Turn
MLCC is played in turns called game-turns.  Each game-turn consist of two
player-turns.  Each player-turn is composed of three phases.  The player whose
player-turn is in progress is call the phasing player.

** Sequence
1) First Player Turn:
   1. Initial Movement Phase. The phasing player may move all, some, or none of
      his units (exception see 11.3) in any direction up to the limit of their
      movement allowance within the restrictions outlined in the movement and
      supply rules.
   2. Combat Phase. The phasing player may attack enemy units adjacent to
      friendly units at his option; combat is resolved as outlined in the combat
      rules.
   3. Second Movement Phase. The phasing player may move all of his units in any
      direction up to the limit of their movement allowance with the
      restrictions outlined in the movement rules.
2) Second Player Turn:
   Repeat steps 1 through 3.  The second player becomes the phasing player and
   moves his own units.

** Game Length
- The number of game turns is determined by the scenario.
- At the end of the last turn the game is over.
- Evaluate the player's performance against mission objectives to determine a
  winner. 

* Movement
** General
- During the movement phase the phasing player may move some, none, or all of
  his units that are eligible to move.  
- A unit may be moved as many or as few hexes as the phasing player desires.
- A unit may not exceed its movement allowance during any of its movement phases.  
- Unused movement points may NOT be accumulated nor transferred to another unit.
- Movement points are reset at the beginning of a turn.

** Procedure
Move each unit individually, tracing a path of its movement through the
hexagonal grid.  One a unit has been moved and the player's hand withdrawn, the
unit may not be moved again, nor the path retraced and/or changed during that
movement phase.

** How to Move
During the movement phase only the phasing player's units are allowed to move;
all, some, or none of his units may be moved.  No enemy movement, and no combat,
may occur during a movement phase.

Movement is calculated in terms of movement points.  Basically each unit expends
one movement point of it's total allowance for each hex it enters.

** Movement Restrictions
A unit's movement allowance may be decreased by supply considerations, lowering
the number of available movement points in a given movement phase.  The number
of movement points to enter a given hex accumulates by addition i.e. to enter a
woods hex while crossing a river the hexside would cost three movement points:
Two for the woods and one for crossing the river (see terrain effects chart).
All effects of reducing available movement points and increasing the number of
movement points to enter a given hex are cumulative.

A unit may always move a single hex in a given movement phase as long as it is
not leaving one enemy controlled hex and directly entering another, and is not
entering a sea hex or crossing a sea hexside (exceptions see 5.4)

** Special Movement Abilities
Airmobile Units.  There are two types of airmobile units airmobile divisions
(composed of one base element and two airmobile elements) and Tricap divisions
(composed of one base element and one airmobile element).  The airmobile element
of these units may ignore all effects of the first enemy controlled hex they
enter in any friendly movement phase, as long as they did not begin that
movement phase in an enemy controlled hex.  If they did begin in an enemy
controlled hex, they may only enter another enemy controlled hex (even an
adjacent one).  Thus airmobile elements have a limited ability to move through
enemy controlled hexes.

Air Transportable Units.  These units have the unique ability to move without
regard to movement allowance and the hex grid.  At the beginning of any friendly
movement phase, any supplied air-transportable unit not in an enemy controlled
hex may be removed from the map and placed on any other hex with four
restrictions: 

1. The may not be placed on enemy occupied or controlled hexes.
2. They may not be placed on all-sea or all-lake hexes.
3. The may not be placed on hexes from which a line of unblocked contiguous
   hexes no longer than twelve hexes may be traced to any friendly supply unit.
   Hexes are blocked by impassable terrain, enemy occupied hexes and enemy
   controlled hexes not occupied by friendly units.
4. They may only air transport from one clear terrain hex to another clear
   terrain hex. 

* Zones of Control
** Movement Effects
- Upon entering an enemy controlled hex a unit must stop and may not move again in
  that movement phase (exception 6.2).  However, units expend no additional
  movement points to enter an enemy controlled hex (only normal terrain costs).
- A unit may never move from one enemy controlled hex directly to another enemy
  controlled hex (see exception 6.2).
- A unit that starts its movement phase in an enemy controlled hex may move out
  and re-enter another enemy controlled hex, providing it does not move directly
  from one to another.  It must first enter at least one non-controlled hex.

** Airmobile Effects
The airmobile elements of Airmobile and Tricap units may move from one enemy
controlled hex directly to another enemy controlled hex once per movement phase
(see 5.4).  They are the only units with this ability.

** Combat Effects
Zones of control do not affect combat attacking is completely voluntary and the
presence of a unit's zone of control in a friendly occupied hex does not force
combat.

** Retreat Effects
Units may not retreat (due to combat; see the CRT) into or through an enemy
controlled hex, unless another friendly unit already occupies the controlled
hex.  Thus, for retreat purposes, enemy controlled hexes are negated by friendly
units.

** Supply Effects
Supply lines may not be traced through enemy controlled hexes unless that hex is
occupied by a friendly unit.  Thus, for supply purposes, friendly units negate
enemy controlled hexes.

* Stacking
The opposing forces may stack a maximum of two units of any type per hex, while
the blue forces player may stack only one division or its equivalent.  A supply
unit counts as a division-sized unit for both sides where stacking is concerned.

** Movement Effect
Units may not move through hexes in violation of the stacking limitations.  The
stacking limit applies at all times during the friendly movement phase.  Units
may not overstack voluntarily.  Thus a unit could not be moved into or through a
hex if the combination of the moving and stationary unit violated stacking
limitations (see 9.2).

** Combat Effect
All units which are in a hex under attack must be attacked; their separate
defense strengths are totaled and the entire combined strength must be attacked.
Units stacked together may not be attacked separately. If one unit in a stack of
units is attacking a given hex, the remaining units are under no compulsion to
join in the attack.  They may attack different hexes, or not attack at all.

** Unit Buildup and Breakdown
The blue forces player may, at his option, break down (i.e. create more, smaller
units from a single unit) or build up (i.e. combine several smaller units into
one stronger unit) certain units into other configurations.  Units to be
combined must be of the same nationality and must start the movement phase
stacked together.  Units when broken down are replaced in the same nationality.
Combining or breaking down requires the expenditure of all eight movement points
from the initiating units.  Units may never change nationality when breaking
down or building up.  Only the blue force player may break down or combine
units.  Building up or breaking down takes place at the beginning of the
friendly movement phase (this should be a command action), and all movement is
denied any units that engage in either operation.  Unit types have no effect on
building up or breaking down, only the units strengths and allowance.

The following substitutions can be made:

Images of units broken into sub units.

* Combat
** General Rule
Combat occurs between adjacent opposing units a the phasing player's
discretion.  The phasing player is the attacker, the non-phasing player the
defender, regardless of their overall strategic position.

** Procedure
Total the combat strengths for all the attacking units in a specific attack
and compare it to the total combat strength of all unit in the hex under
attack.  State the comparison as a probability ration: attacker's strength to
defender's strength.  Round off the ratio in favor of the defender to conform
to the simplified odds found on the combat results table, roll the die and
read the result on the appropriate line under odds.  Apply the result
immediately, before resolving any other attacks being made during that combat
phase.

** Which Units May Attack
1. During the combat phase of his player-turn, the phasing player may attack any
   and all enemy units adjacent to friendly units.  Only those friendly units
   directly adjacent to a given enemy unit may participate in an attack upon that
   unit.

2. Attacking is completely voluntary; units are never compelled to attack, and not
   every unit adjacent to an enemy unit need participate in any attack.  Friendly
   units in a stack that are not participating in a given attack are never affected
   by the results of an attack.

3. An enemy occupied hex may be attacked by as many units as can be brought to
   bear in the six adjacent hexes.

4. No unit may attack more than once per combat phase, and no enemy unit may be
   attacked more than once per combat phase.

** Multiple Unit and Multi-hex Combat
- All units defending in a given hex must be involved in the combat, and they
  must all be attacked as a single strength.  The defender may not voluntarily
  withhold any units in a hex under attack.  The attacker must attack all the
  units as a whole, i.e., the strengths of all the units in the hex are totaled,
  and this total strength is attacked.  Different units in a given hex may not,
  therefore, be attacked separately.

- Other units in a hex that contains an attacking unit need not participate in
  that same attack or any other attack.  Thus when one unit in a stack of three
  is attacking a given hex, one or the other units could attack a different hex,
  and the third could participate in no attack.

- If a unit or units is adjacent to more than one enemy-occupied hex, it could
  attack all of them in a single combat.  Thus units in a single hex can attack
  more than one other hex.  the only requirement is that all attacking units
  must be adjacent to all defending units.

** Combat Odds Calculation
Combat odds are always rounded off in favor of the defender.  For example, an
attack with a combat strength of 26 points against a hex defending with nine
strength points, for an odds ratio of 26:9, would round off to a 2-1 combat
situation for combat resolution purposes.  That column on the combat results
table would be used.

** Effect on Unit Strength
Combat strengths of units may be affected by terrain and supply considerations
(see terrain effects chart and the supply rules).  This is always expressed as
the combat strength being "halved", all fractions are retained.  This an
unsupplied unit attacking across a river hexside would be quartered in attack
strength (halved and then halved again).  In this case a unit with an attack
strength of five would effectively use 1.25 strength points in the attack.
 
** NATO Battlegroups
1. If, due to any combat result (De, Ae, or Ex) a blue forces 5-5-8 or 6-6-8
   unit is eliminated, it is removed from the map and replaced with a
   "battlegroup" unit (1-2-8). Only blue force 5-5-8 or 6-6-8 units receive this
   benefit. The battlegroup unit is immediately placed on the hex in which the
   blue force 5-5-8 or 6-6-8 unit was eliminated, and suffers no further combat
   effects in that phase. This, if the original unit was eliminated due to
   inability to retreat, the battlegroup unit need not retreat (however, see
   Nuclear Combat Rules).

2. In cases where a battlegroup unit is formed due to an "Exchange" combat result,
   the opposing force player must still remove a number of strength points equal
   to or greater than the original unit, not the original unit minus the strength
   points of the battlegroup formed.

3. Battlegroup units are identical in all ways to regular brigades of their
   respective nationality, i.e. they are considered brigades for stacking
   purposes and may be used as such in building units (see 7.3).  Unit types may
   be ignored in replacing with battlegroups.

* Combat Results Table

          Combat odds (Attack Strength / Defense Strength
| DR | 1-1 | 2-1 | 3-1 | 4-1 | 5-1 | 6-1 | 7-1 | 8-1 | 9-1 | 10-1 |
|----+-----+-----+-----+-----+-----+-----+-----+-----+-----+------|
|  1 | Dr1 | Dr2 | Dr2 | Dr2 | Dr3 | Dr3 | Dr3 | De  | De  | De   |
|  2 | Dr1 | Dr1 | Dr2 | Dr2 | Dr2 | Dr3 | Dr3 | Dr3 | De  | De   |
|  3 | Ar1 | Dr1 | Dr1 | Dr2 | Dr2 | Dr2 | Dr3 | Dr3 | Dr3 | De   |
|  4 | Ar1 | Ar1 | Dr1 | Dr1 | Dr1 | Dr2 | Dr3 | Dr3 | Dr3 | Ex   |
|  5 | Ar1 | Ex  | Ex  | Dr1 | Dr1 | Dr2 | Ex  | Ex  | Ex  | Ex   |
|  6 | Ae  | Ae  | Ar1 | Ex  | Ex  | Ex  | Ex  | Ex  | Ex  | Ex   |

Odds less than 1-1 are NOT permitted; Odds greater than 10-1 are treated as
10-1.

** Explanation of Results
** How to Retreat
** Advance After Combat

* Terrain Effects Chart

* Supply
** Supply Source and Lines
** Warsaw Pact Supply Limitations
** Supply Unit Movement
** Reinforcements
** Blocking Supply Lines
** Supply Effects Chart
