#+TITLE: Modern Land Combat Commander
#+STARTUP: indent

* Introduction 
MLCC is a simulation of modern brigade/division level conflict between forces of
equal abilities.
 
* General Course of Play
MLCC is a two-player game.  Each player moves his units and executes attacks
on enemy units in turn, attempting to fulfill the conditions of victory.  To
move from one hex to another, each unit expends a portion of its movement
allowance.  Combat is resolved by comparing the total combat strength of
adjacent opposing units and expressing the comparison as a simplified
probability ratio (odds).  A dies is rolled and the outcome indicated on the
combat results table is applies to the units involved.

* Game Files
There are several game files that are required to play the game.
- Map image.  This is a simple jpg image that serves as a visual reference for
  the player.
- Map Terrain File.  This file defines the terrain for the map.
- Scenario file.  This file defines the operational environment for a specific
  scenario.
- Unit and game icons.  These files are png or jpg and depict units and other
  game functions.

* Map
- The game map is a 2d representation of a land-based area of operations.
- A hexagonal grid is superimposed upon the map image to control movement and
  combat of the units, tracing supply lines, and delineating the terrain imposed
  on the map.
** Requirements
- The image format for the map is jpg.
- Map colors to be determined.  Flashpoint Campaign values.
- Individual hex for the grid is 72 px tall with the flat side facing up.
- Size of the map can vary depending on the operations area.
*** Terrain File
The terrain file defines the terrain elements for a specific map.
- json format??
- Terrain movement costs (see terrain effects table).
- Combat modifiers.

* Units
- Icons use NATO symbols and represent different units from the opposing forces.
** Requirements
- The image format for unit and game icons is jpg or png.
- Texture map??
 
* Charts and Tables
* Scale
- Combat units represent battalions and brigades.
- Some combat such as Artillery or Air Defense may be represented by batterys or
  platoons.
- Hexes represent 5 to 10 kms on the ground.
- Each turn represents 3 to 6 hours of time.

* Scenario File
The scenario file defines the operational environment for the game.
- Orders of battle for both sides.  The order of battle specifies which units
  will be available for the scenario.
- Map image and corresponding terrain file.
- Weather conditions.
- Mission objectives.
- Operations order file.  This is a link to the OPORD briefing which provides
  the player with the information they need to plan their mission.
- json format?
* Sequence of Play
** The Game-Turn
MLCC is played in turns called game-turns.  Each game-turn consist of two
player-turns.  Each player-turn is composed of three phases.  The player whose
player-turn is in progress is call the phasing player.

** Sequence
1) First Player Turn:
   1. Initial Movement Phase. The phasing player may move all, some, or none of
      his units (exception see 11.3) in any direction up to the limit of their
      movement allowance within the restrictions outlined in the movement and
      supply rules.
   2. Combat Phase. The phasing player may attack enemy units adjacent to
      friendly units at his option; combat is resolved as outlined in the combat
      rules.
   3. Second Movement Phase. The phasing player may move all of his units in any
      direction up to the limit of their movement allowance with the
      restrictions outlined in the movement rules.
2) Second Player Turn:
   Repeat steps 1 through 3.  The second player becomes the phasing player and
   moves his own units.

** Game Length
- The number of game turns is determined by the scenario.
- At the end of the last turn the game is over.
- Evaluate the player's performance against mission objectives to determine a
  winner. 

* Movement
** General
- During the movement phase the phasing player may move some, none, or all of
  his units that are eligible to move.  
- A unit may be moved as many or as few hexes as the phasing player desires.
- A unit may not exceed its movement allowance during any of its movement phases.  
- Unused movement points may NOT be accumulated nor transferred to another unit.
- Movement points are reset at the beginning of a turn.

**Procedure
** How to Move
** Movement Restrictions
** Special Movement Abilities

* Zones of Control
** Movement Effects
** Airmobile Effects
** Combat Effects
** Retreat Effects
** Supply Effects

* Stacking
** Movement Effect
** Combat Effect
** Unit Buildup and Breakdown

* Combat
** Which Units May Attack
** Multiple Unit and Multi-hex Combat
** Combat Odds Calculation
** Effect on Unit Strength
** NATO Battlegroups

* Combat Results Table
** Explanation of Results
** How to Retreat
** Advance After Combat

* Terrain Effects Chart

* Supply
** Supply Source and Lines
** Warsaw Pact Supply Limitations
** Supply Unit Movement
** Reinforcements
** Blocking Supply Lines
** Supply Effects Chart
